from __future__ import annotations

import textwrap
import uuid
from datetime import datetime, timezone

import structlog
from fastapi import APIRouter, HTTPException, status

from app.models.schemas import (
    APIResponse,
    MQL5CompileRequest,
    MQL5CompileResponse,
    MQL5GenerateRequest,
    MQL5GenerateResponse,
    MQL5InstallRequest,
    MQL5Type,
)

logger = structlog.get_logger("jarvis.mql5")
router = APIRouter(prefix="/mql5", tags=["MQL5 Code Generation"])

_generated_files: dict[str, MQL5GenerateResponse] = {}


def _generate_ea_code(request: MQL5GenerateRequest) -> str:
    params_block = "\n".join(
        f"input {p.param_type} {p.name} = {p.value};  // {p.description}"
        for p in request.parameters
    ) if request.parameters else "input double LotSize = 0.1;  // Trading lot size"

    return textwrap.dedent(f"""\
        //+------------------------------------------------------------------+
        //| {request.name}.mq5
        //| Generated by JARVIS Trading OS
        //| Description: {request.description or 'Expert Advisor'}
        //+------------------------------------------------------------------+
        #property copyright "JARVIS Trading OS"
        #property link      "https://jarvis-trading.com"
        #property version   "1.00"
        #property strict

        #include <Trade\\Trade.mqh>

        {params_block}
        input int    MagicNumber  = 123456;
        input int    Slippage     = 20;

        CTrade trade;
        int    onInitResult;

        //+------------------------------------------------------------------+
        int OnInit()
        {{
            trade.SetExpertMagicNumber(MagicNumber);
            trade.SetDeviationInPoints(Slippage);
            trade.SetTypeFilling(ORDER_FILLING_IOC);

            Print("{request.name} initialized successfully");
            return INIT_SUCCEEDED;
        }}

        //+------------------------------------------------------------------+
        void OnDeinit(const int reason)
        {{
            Print("{request.name} deinitialized. Reason: ", reason);
        }}

        //+------------------------------------------------------------------+
        void OnTick()
        {{
            if(!IsNewBar())
                return;

            // ── Entry logic ──────────────────────────────────────────────
            {_format_rules(request.entry_rules, "entry")}

            // ── Exit logic ───────────────────────────────────────────────
            {_format_rules(request.exit_rules, "exit")}
        }}

        //+------------------------------------------------------------------+
        bool IsNewBar()
        {{
            static datetime lastBarTime = 0;
            datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
            if(currentBarTime != lastBarTime)
            {{
                lastBarTime = currentBarTime;
                return true;
            }}
            return false;
        }}

        //+------------------------------------------------------------------+
        double CalculateLotSize(double riskPercent, double stopLossPips)
        {{
            double accountBalance = AccountInfoDouble(ACCOUNT_BALANCE);
            double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
            double tickSize  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
            double pointSize = SymbolInfoDouble(_Symbol, SYMBOL_POINT);

            if(tickValue == 0 || pointSize == 0)
                return 0.01;

            double riskAmount = accountBalance * riskPercent / 100.0;
            double lotSize = riskAmount / (stopLossPips * (tickValue / tickSize) * pointSize);
            double minLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
            double maxLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
            double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);

            lotSize = MathFloor(lotSize / lotStep) * lotStep;
            lotSize = MathMax(minLot, MathMin(maxLot, lotSize));

            return NormalizeDouble(lotSize, 2);
        }}
        //+------------------------------------------------------------------+
    """)


def _generate_indicator_code(request: MQL5GenerateRequest) -> str:
    params_block = "\n".join(
        f"input {p.param_type} {p.name} = {p.value};"
        for p in request.parameters
    ) if request.parameters else "input int Period = 14;"

    return textwrap.dedent(f"""\
        //+------------------------------------------------------------------+
        //| {request.name}.mq5
        //| Generated by JARVIS Trading OS
        //| Description: {request.description or 'Custom Indicator'}
        //+------------------------------------------------------------------+
        #property copyright "JARVIS Trading OS"
        #property link      "https://jarvis-trading.com"
        #property version   "1.00"
        #property indicator_chart_window
        #property indicator_buffers 2
        #property indicator_plots   2

        #property indicator_label1  "Signal Up"
        #property indicator_type1   DRAW_ARROW
        #property indicator_color1  clrLime
        #property indicator_width1  2

        #property indicator_label2  "Signal Down"
        #property indicator_type2   DRAW_ARROW
        #property indicator_color2  clrRed
        #property indicator_width2  2

        {params_block}

        double SignalUpBuffer[];
        double SignalDownBuffer[];

        //+------------------------------------------------------------------+
        int OnInit()
        {{
            SetIndexBuffer(0, SignalUpBuffer, INDICATOR_DATA);
            SetIndexBuffer(1, SignalDownBuffer, INDICATOR_DATA);

            PlotIndexSetInteger(0, PLOT_ARROW, 233);
            PlotIndexSetInteger(1, PLOT_ARROW, 234);

            PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
            PlotIndexSetDouble(1, PLOT_EMPTY_VALUE, EMPTY_VALUE);

            IndicatorSetString(INDICATOR_SHORTNAME, "{request.name}");

            return INIT_SUCCEEDED;
        }}

        //+------------------------------------------------------------------+
        int OnCalculate(const int rates_total,
                        const int prev_calculated,
                        const datetime &time[],
                        const double &open[],
                        const double &high[],
                        const double &low[],
                        const double &close[],
                        const long &tick_volume[],
                        const long &volume[],
                        const int &spread[])
        {{
            int start = MathMax(prev_calculated - 1, 1);
            for(int i = start; i < rates_total; i++)
            {{
                SignalUpBuffer[i]   = EMPTY_VALUE;
                SignalDownBuffer[i] = EMPTY_VALUE;

                // Signal logic placeholder
                if(close[i] > open[i] && close[i-1] < open[i-1])
                    SignalUpBuffer[i] = low[i];
                else if(close[i] < open[i] && close[i-1] > open[i-1])
                    SignalDownBuffer[i] = high[i];
            }}
            return rates_total;
        }}
        //+------------------------------------------------------------------+
    """)


def _format_rules(rules: str, kind: str) -> str:
    if not rules:
        return f"// TODO: Implement {kind} rules"
    lines = rules.strip().split("\n")
    return "\n            ".join(f"// {line}" for line in lines)


# ── Generate EA ──────────────────────────────────────────────────────────

@router.post(
    "/generate/ea",
    response_model=APIResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Generate an MQL5 Expert Advisor",
)
async def generate_ea(request: MQL5GenerateRequest) -> APIResponse:
    logger.info("mql5_generate_ea", name=request.name)

    code = _generate_ea_code(request)
    filename = f"{request.name.replace(' ', '_')}.mq5"

    result = MQL5GenerateResponse(
        filename=filename,
        code=code,
        mql_type=MQL5Type.EA,
        warnings=[],
    )
    _generated_files[filename] = result

    return APIResponse(
        success=True,
        message=f"Expert Advisor '{request.name}' generated.",
        data=result.model_dump(mode="json"),
    )


# ── Generate indicator ───────────────────────────────────────────────────

@router.post(
    "/generate/indicator",
    response_model=APIResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Generate an MQL5 custom indicator",
)
async def generate_indicator(request: MQL5GenerateRequest) -> APIResponse:
    logger.info("mql5_generate_indicator", name=request.name)

    code = _generate_indicator_code(request)
    filename = f"{request.name.replace(' ', '_')}.mq5"

    result = MQL5GenerateResponse(
        filename=filename,
        code=code,
        mql_type=MQL5Type.INDICATOR,
        warnings=[],
    )
    _generated_files[filename] = result

    return APIResponse(
        success=True,
        message=f"Indicator '{request.name}' generated.",
        data=result.model_dump(mode="json"),
    )


# ── Compile ──────────────────────────────────────────────────────────────

@router.post(
    "/compile",
    response_model=APIResponse,
    summary="Compile MQL5 source code",
)
async def compile_mql5(request: MQL5CompileRequest) -> APIResponse:
    logger.info("mql5_compile", filename=request.filename)

    errors: list[str] = []
    warnings: list[str] = []

    if "#property" not in request.code:
        warnings.append("Missing #property directives.")
    if "OnInit" not in request.code and "OnCalculate" not in request.code:
        errors.append("No entry point found (OnInit or OnCalculate required).")
    if "OnTick" not in request.code and "OnCalculate" not in request.code:
        warnings.append("No OnTick or OnCalculate handler found.")

    result = MQL5CompileResponse(
        success=len(errors) == 0,
        filename=request.filename.replace(".mq5", ".ex5"),
        errors=errors,
        warnings=warnings,
    )

    if result.success:
        logger.info("mql5_compile_success", filename=request.filename)
    else:
        logger.warning(
            "mql5_compile_failed",
            filename=request.filename,
            errors=errors,
        )

    return APIResponse(
        success=result.success,
        message="Compilation successful." if result.success else "Compilation failed.",
        data=result.model_dump(mode="json"),
    )


# ── Install to MT5 ──────────────────────────────────────────────────────

@router.post(
    "/install",
    response_model=APIResponse,
    summary="Install compiled file to MT5 terminal",
)
async def install_to_mt5(request: MQL5InstallRequest) -> APIResponse:
    logger.info(
        "mql5_install",
        filename=request.filename,
        type=request.mql_type.value,
    )

    type_dirs = {
        MQL5Type.EA: "Experts",
        MQL5Type.INDICATOR: "Indicators",
        MQL5Type.SCRIPT: "Scripts",
    }
    target_dir = type_dirs.get(request.mql_type, "Experts")

    return APIResponse(
        success=True,
        message=f"File '{request.filename}' queued for installation to MQL5/{target_dir}/.",
        data={
            "filename": request.filename,
            "target_directory": f"MQL5/{target_dir}/",
            "status": "queued",
        },
    )


# ── List generated files ────────────────────────────────────────────────

@router.get(
    "/files",
    response_model=APIResponse,
    summary="List all generated MQL5 files",
)
async def list_generated_files() -> APIResponse:
    items = [
        {"filename": f.filename, "type": f.mql_type.value}
        for f in _generated_files.values()
    ]
    return APIResponse(success=True, data=items)


# ── Get generated file ──────────────────────────────────────────────────

@router.get(
    "/files/{filename}",
    response_model=APIResponse,
    summary="Get a generated MQL5 file",
)
async def get_generated_file(filename: str) -> APIResponse:
    result = _generated_files.get(filename)
    if not result:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"File '{filename}' not found.",
        )
    return APIResponse(success=True, data=result.model_dump(mode="json"))
