from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from textwrap import dedent
from typing import Any

from ghost_security import SecurityAuditor


@dataclass
class AppSpec:
    name: str
    description: str
    app_type: str
    features: list[str]


@dataclass
class AppGenerationResult:
    app_name: str
    app_path: str
    generated_files: list[str]
    audit_summary: dict[str, Any]
    generated_at: str


class PythonAppGenerator:
    def __init__(self, base_dir: str | Path, auditor: SecurityAuditor | None = None) -> None:
        self.base_dir = Path(base_dir)
        self.base_dir.mkdir(parents=True, exist_ok=True)
        self.auditor = auditor or SecurityAuditor()

    def _slugify(self, value: str) -> str:
        slug = re.sub(r"[^a-zA-Z0-9]+", "_", value.strip().lower()).strip("_")
        return slug or "jarvis_app"

    def _infer_type(self, prompt: str) -> str:
        lowered = prompt.lower()
        if "streamlit" in lowered or "dashboard" in lowered:
            return "streamlit"
        if "api" in lowered or "fastapi" in lowered:
            return "api"
        return "cli"

    def _infer_name(self, prompt: str) -> str:
        quoted = re.findall(r"'([^']+)'|\"([^\"]+)\"", prompt)
        if quoted:
            name = next(filter(None, quoted[0]))
            return self._slugify(name)
        token_match = re.search(r"app\s+([a-zA-Z0-9_-]+)", prompt, re.I)
        if token_match:
            return self._slugify(token_match.group(1))
        words = prompt.split()
        return self._slugify("_".join(words[:3]))

    def parse_prompt(self, prompt: str) -> AppSpec:
        name = self._infer_name(prompt)
        app_type = self._infer_type(prompt)
        feature_tokens = re.findall(r"\b[a-zA-Z][a-zA-Z0-9_-]{3,}\b", prompt.lower())
        common = {
            "build",
            "create",
            "generate",
            "python",
            "with",
            "that",
            "this",
            "streamlit",
            "dashboard",
            "fastapi",
            "app",
        }
        features = [token for token in feature_tokens if token not in common][:6]
        return AppSpec(
            name=name,
            description=prompt.strip() or f"{name} generated by JARVIS",
            app_type=app_type,
            features=features or ["healthcheck", "logging", "configuration"],
        )

    def _build_main_template(self, spec: AppSpec) -> str:
        if spec.app_type == "streamlit":
            return dedent(
                f"""
                import streamlit as st

                st.set_page_config(page_title="{spec.name}", layout="wide")
                st.title("{spec.name.replace('_', ' ').title()}")
                st.caption("{spec.description}")

                st.subheader("Feature deck")
                for feature in {spec.features!r}:
                    st.write(f"- {{feature}}")

                st.success("Application booted successfully.")
                """
            ).strip() + "\n"

        if spec.app_type == "api":
            return dedent(
                f"""
                from fastapi import FastAPI

                app = FastAPI(title="{spec.name.replace('_', ' ').title()}")


                @app.get("/health")
                def health() -> dict[str, str]:
                    return {{"status": "ok", "service": "{spec.name}"}}


                @app.get("/features")
                def features() -> dict[str, list[str]]:
                    return {{"features": {spec.features!r}}}
                """
            ).strip() + "\n"

        return dedent(
            f"""
            import argparse
            import json


            def main() -> None:
                parser = argparse.ArgumentParser(description="{spec.description}")
                parser.add_argument("--json", action="store_true", help="Print machine-readable output.")
                args = parser.parse_args()
                payload = {{
                    "app": "{spec.name}",
                    "features": {spec.features!r},
                    "status": "ready",
                }}
                if args.json:
                    print(json.dumps(payload, indent=2))
                else:
                    print("Application: {spec.name}")
                    print("Features:")
                    for feature in payload["features"]:
                        print(f" - {{feature}}")


            if __name__ == "__main__":
                main()
            """
        ).strip() + "\n"

    def _build_config_template(self, spec: AppSpec) -> str:
        return dedent(
            f"""
            APP_NAME = "{spec.name}"
            APP_DESCRIPTION = "{spec.description}"
            APP_TYPE = "{spec.app_type}"
            FEATURES = {spec.features!r}
            """
        ).strip() + "\n"

    def _build_readme_template(self, spec: AppSpec) -> str:
        return dedent(
            f"""
            # {spec.name.replace('_', ' ').title()}

            {spec.description}

            ## Features
            {"".join(f"- {feature}\n" for feature in spec.features)}
            ## Run

            ```bash
            python main.py
            ```
            """
        ).strip() + "\n"

    def _build_test_template(self, spec: AppSpec) -> str:
        return dedent(
            f"""
            from pathlib import Path


            def test_generated_files_exist() -> None:
                app_dir = Path(__file__).resolve().parents[1]
                assert (app_dir / "main.py").exists()
                assert (app_dir / "config.py").exists()
                assert "{spec.name}"
            """
        ).strip() + "\n"

    def _write_files(self, app_dir: Path, spec: AppSpec) -> list[str]:
        files = {
            app_dir / "main.py": self._build_main_template(spec),
            app_dir / "config.py": self._build_config_template(spec),
            app_dir / "README.md": self._build_readme_template(spec),
            app_dir / "__init__.py": "",
            app_dir / "tests" / "test_smoke.py": self._build_test_template(spec),
        }
        generated_files: list[str] = []
        for path, content in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            generated_files.append(str(path))
        return generated_files

    def generate_app(self, spec: AppSpec) -> AppGenerationResult:
        app_dir = self.base_dir / spec.name
        app_dir.mkdir(parents=True, exist_ok=True)
        generated_files = self._write_files(app_dir, spec)
        audit = self.auditor.scan_directory(app_dir)
        return AppGenerationResult(
            app_name=spec.name,
            app_path=str(app_dir),
            generated_files=generated_files,
            audit_summary=audit,
            generated_at=datetime.now(timezone.utc).isoformat(),
        )

    def generate_from_prompt(self, prompt: str) -> dict[str, Any]:
        spec = self.parse_prompt(prompt)
        result = self.generate_app(spec)
        return asdict(result)


def main() -> None:
    generator = PythonAppGenerator(Path(__file__).resolve().parent / "apps")
    payload = generator.generate_from_prompt("Generate a CLI app for operational reporting")
    print(json.dumps(payload, indent=2))


if __name__ == "__main__":
    main()
