"""
JARVIS CODING CORE
------------------

Deterministic Python app generator for the /apps workspace. It creates runnable
Streamlit or CLI applications from structured specifications and audits the
result immediately after writing.
"""

from __future__ import annotations

import re
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from ghost_security import AuditFinding, SecurityAuditor


APP_ROOT = Path("apps")
SAFE_NAME = re.compile(r"[^a-zA-Z0-9_-]+")


@dataclass(frozen=True)
class AppSpec:
    name: str
    purpose: str
    interface: Literal["streamlit", "cli"] = "streamlit"
    features: tuple[str, ...] = field(default_factory=tuple)
    owner_title: str = "Sir"


@dataclass(frozen=True)
class GeneratedApp:
    path: Path
    code: str
    audit_findings: tuple[AuditFinding, ...]


class JarvisCoder:
    def __init__(self, app_root: Path = APP_ROOT) -> None:
        self.app_root = app_root
        self.app_root.mkdir(parents=True, exist_ok=True)

    def generate(self, spec: AppSpec, overwrite: bool = False) -> GeneratedApp:
        safe_name = self._safe_name(spec.name)
        target = self.app_root / f"{safe_name}.py"
        if target.exists() and not overwrite:
            raise FileExistsError(f"{target} already exists; pass overwrite=True to replace it")
        code = self._render(spec)
        compile(code, str(target), "exec")
        target.write_text(code, encoding="utf-8")
        findings = tuple(SecurityAuditor([target]).scan())
        return GeneratedApp(path=target, code=code, audit_findings=findings)

    def _render(self, spec: AppSpec) -> str:
        if spec.interface == "streamlit":
            return self._render_streamlit(spec)
        return self._render_cli(spec)

    def _render_streamlit(self, spec: AppSpec) -> str:
        feature_lines = "\n".join(
            f"    st.success({feature!r})" for feature in (spec.features or ("Operational status panel",))
        )
        return textwrap.dedent(
            f'''\
            """
            Generated by JARVIS Coding Core.
            Purpose: {spec.purpose}
            """

            from __future__ import annotations

            from datetime import datetime, timezone

            import streamlit as st


            def main() -> None:
                st.set_page_config(page_title={spec.name!r}, layout="wide")
                st.title({spec.name!r})
                st.caption("Good day, {spec.owner_title}. Generated app online.")
                st.write({spec.purpose!r})
                st.metric("Runtime", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"))
                st.subheader("Enabled features")
            {feature_lines}


            if __name__ == "__main__":
                main()
            '''
        )

    def _render_cli(self, spec: AppSpec) -> str:
        features = ", ".join(spec.features) if spec.features else "Operational status panel"
        return textwrap.dedent(
            f'''\
            """
            Generated by JARVIS Coding Core.
            Purpose: {spec.purpose}
            """

            from __future__ import annotations

            from datetime import datetime, timezone


            def main() -> None:
                print("Good day, {spec.owner_title}.")
                print({spec.name!r})
                print({spec.purpose!r})
                print("Features: {features}")
                print(datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"))


            if __name__ == "__main__":
                main()
            '''
        )

    @staticmethod
    def _safe_name(name: str) -> str:
        lowered = SAFE_NAME.sub("_", name.strip().lower()).strip("_")
        if not lowered:
            raise ValueError("App name must contain at least one alphanumeric character")
        return lowered[:80]


def generate_default_app() -> GeneratedApp:
    coder = JarvisCoder()
    return coder.generate(
        AppSpec(
            name="jarvis_status_console",
            purpose="Operational status console for generated JARVIS applications.",
            features=("Health metrics", "Security audit summary", "Operator notes"),
        ),
        overwrite=True,
    )


if __name__ == "__main__":
    app = generate_default_app()
    print(f"Generated {app.path}")
    for finding in app.audit_findings:
        print(f"{finding.severity.upper()} {finding.path}:{finding.line} {finding.rule}")
