from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
import json
import py_compile
import re
from typing import Any, Dict, List, Optional

from ghost_security import SecurityAuditScanner


@dataclass
class GenerationResult:
    app_name: str
    app_path: str
    app_type: str
    created_files: List[str] = field(default_factory=list)
    compile_ok: bool = False
    audit_summary: Dict[str, Any] = field(default_factory=dict)
    audit_report: Optional[str] = None
    metadata_file: Optional[str] = None


class JarvisCodingCore:
    """Generates production-ready Python app scaffolds under /apps."""

    def __init__(self, apps_root: str = "apps") -> None:
        self.apps_root = Path(apps_root).resolve()
        self.apps_root.mkdir(parents=True, exist_ok=True)
        self.audit = SecurityAuditScanner(root=str(self.apps_root))

    @staticmethod
    def _slugify(name: str) -> str:
        slug = re.sub(r"[^a-zA-Z0-9_-]+", "-", name.strip().lower()).strip("-")
        return slug or "jarvis-app"

    @staticmethod
    def _safe_title(name: str) -> str:
        return " ".join(part.capitalize() for part in re.split(r"[-_ ]+", name) if part)

    def _build_cli_main(self, app_name: str, title: str, description: str, features: List[str]) -> str:
        feature_lines = "\n".join(f"    - {feat}" for feat in features) if features else "    - core command execution"
        return f'''from __future__ import annotations

import argparse
from datetime import datetime


def run_task(task: str) -> str:
    now = datetime.utcnow().isoformat()
    return f"[{{now}}] {title} executed task: {{task}}"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="{app_name}", description="{description}")
    parser.add_argument("task", help="Task to execute")
    parser.add_argument("--verbose", action="store_true", help="Enable verbose output")
    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    output = run_task(args.task)
    if args.verbose:
        print("Feature set:")
        print("""{feature_lines}
""")
    print(output)


if __name__ == "__main__":
    main()
'''

    def _build_streamlit_main(self, title: str, description: str, features: List[str]) -> str:
        feature_md = "\n".join(f"- {feat}" for feat in features) if features else "- Core dashboard mode"
        return f'''from __future__ import annotations

import pandas as pd
import streamlit as st


st.set_page_config(page_title="{title}", layout="wide")
st.title("{title}")
st.caption("{description}")

st.markdown("### Features")
st.markdown("""{feature_md}""")

with st.sidebar:
    size = st.slider("Data points", min_value=20, max_value=200, value=80)
    seed = st.number_input("Seed", min_value=1, max_value=9999, value=42)

data = pd.DataFrame({{"x": range(size)}})
data["y"] = (data["x"] * 1.7 + seed) % 100

st.line_chart(data.set_index("x")["y"])
st.success("Application is active.")
'''

    def _build_fastapi_main(self, title: str, description: str, features: List[str]) -> str:
        return f'''from __future__ import annotations

from datetime import datetime
from fastapi import FastAPI


app = FastAPI(title="{title}", description="{description}", version="1.0.0")


@app.get("/health")
def health() -> dict:
    return {{"status": "ok", "time": datetime.utcnow().isoformat()}}


@app.get("/features")
def list_features() -> dict:
    return {{"features": {features!r}}}
'''

    def _build_pyproject(self, app_name: str, app_type: str) -> str:
        deps = {
            "cli": ['"python>=3.10"'],
            "streamlit": ['"python>=3.10"', '"streamlit>=1.45.1"', '"pandas>=2.2.2"'],
            "fastapi": ['"python>=3.10"', '"fastapi>=0.115.12"', '"uvicorn>=0.34.2"'],
        }.get(app_type, ['"python>=3.10"'])
        dep_section = ",\n  ".join(deps)
        return f"""[project]
name = "{app_name}"
version = "0.1.0"
description = "Generated by JARVIS Coding Core"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  {dep_section}
]
"""

    def generate_app(
        self,
        name: str,
        description: str,
        app_type: str = "cli",
        features: Optional[List[str]] = None,
    ) -> GenerationResult:
        app_type = app_type.lower().strip()
        if app_type not in {"cli", "streamlit", "fastapi"}:
            raise ValueError("app_type must be one of: cli, streamlit, fastapi")
        features = features or []

        app_slug = self._slugify(name)
        title = self._safe_title(app_slug)
        app_path = self.apps_root / app_slug
        app_path.mkdir(parents=True, exist_ok=True)
        src_path = app_path / "src"
        src_path.mkdir(parents=True, exist_ok=True)

        readme = f"""# {title}

{description}

## Type
{app_type}

## Features
{chr(10).join(f"- {feature}" for feature in features) if features else "- core mode"}
"""
        if app_type == "cli":
            main_py = self._build_cli_main(app_name=app_slug, title=title, description=description, features=features)
        elif app_type == "streamlit":
            main_py = self._build_streamlit_main(title=title, description=description, features=features)
        else:
            main_py = self._build_fastapi_main(title=title, description=description, features=features)

        files = {
            app_path / "README.md": readme,
            app_path / "pyproject.toml": self._build_pyproject(app_slug, app_type),
            src_path / "__init__.py": "",
            src_path / "main.py": main_py,
        }

        created_files: List[str] = []
        for file_path, content in files.items():
            file_path.write_text(content, encoding="utf-8")
            created_files.append(str(file_path))

        compile_ok = True
        for file_path in files:
            if file_path.suffix != ".py":
                continue
            try:
                py_compile.compile(str(file_path), doraise=True)
            except Exception:
                compile_ok = False

        findings = self.audit.scan(targets=[str(app_path)])
        report_path = self.audit.export_report(findings, out_file=f"{app_slug}_audit.json")
        summary = self.audit.summarize(findings)

        metadata = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "app_name": app_slug,
            "title": title,
            "description": description,
            "app_type": app_type,
            "features": features,
            "created_files": created_files,
            "compile_ok": compile_ok,
            "audit_summary": summary,
            "audit_report": report_path,
        }
        metadata_file = app_path / "jarvis_generation.json"
        metadata_file.write_text(json.dumps(metadata, indent=2), encoding="utf-8")

        return GenerationResult(
            app_name=app_slug,
            app_path=str(app_path),
            app_type=app_type,
            created_files=created_files,
            compile_ok=compile_ok,
            audit_summary=summary,
            audit_report=report_path,
            metadata_file=str(metadata_file),
        )


if __name__ == "__main__":
    core = JarvisCodingCore()
    result = core.generate_app(
        name="signal-inspector",
        description="Inspects market signals generated by JARVIS",
        app_type="cli",
        features=["market snapshots", "structured logs", "json export"],
    )
    print(json.dumps(result.__dict__, indent=2))
