"""Custom MQL5 indicator code generator."""
import logging
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional

from jinja2 import Environment, BaseLoader

logger = logging.getLogger(__name__)


class DrawingStyle(Enum):
    LINE = "DRAW_LINE"
    HISTOGRAM = "DRAW_HISTOGRAM"
    ARROW = "DRAW_ARROW"
    SECTION = "DRAW_SECTION"
    ZIGZAG = "DRAW_ZIGZAG"
    COLOR_LINE = "DRAW_COLOR_LINE"
    FILLING = "DRAW_FILLING"
    NONE = "DRAW_NONE"


class IndicatorType(Enum):
    MOVING_AVERAGE = "moving_average"
    RSI = "rsi"
    BOLLINGER_BANDS = "bollinger_bands"
    MACD = "macd"
    ATR = "atr"
    STOCHASTIC = "stochastic"
    CUSTOM = "custom"


@dataclass
class BufferSpec:
    """Specification for a single indicator buffer."""
    name: str
    label: str = ""
    style: DrawingStyle = DrawingStyle.LINE
    color: str = "clrDodgerBlue"
    width: int = 1
    line_style: str = "STYLE_SOLID"


@dataclass
class IndicatorConfig:
    """Configuration for generating a custom indicator."""
    name: str = "JARVIS_Indicator"
    indicator_type: IndicatorType = IndicatorType.CUSTOM
    short_name: str = ""
    buffers: List[BufferSpec] = field(default_factory=list)
    inputs: str = ""
    window: str = "indicator_chart_window"
    on_calculate_body: str = ""
    on_init_extra: str = ""
    on_deinit_extra: str = ""
    custom_functions: str = ""
    levels: List[float] = field(default_factory=list)
    minimum: Optional[float] = None
    maximum: Optional[float] = None


_INDICATOR_TEMPLATE = """\
//+------------------------------------------------------------------+
//|                                          {{ name }}.mq5           |
//|                        Generated by JARVIS AI Trading OS          |
//+------------------------------------------------------------------+
#property copyright "JARVIS AI Trading OS"
#property link      ""
#property version   "1.00"
#property strict
#property {{ window }}

#property indicator_buffers {{ buffer_count }}
#property indicator_plots   {{ plot_count }}

{% for buf in buffers %}
//--- Plot {{ buf.name }}
#property indicator_label{{ loop.index }}  "{{ buf.label or buf.name }}"
#property indicator_type{{ loop.index }}   {{ buf.style.value }}
#property indicator_color{{ loop.index }}  {{ buf.color }}
#property indicator_style{{ loop.index }}  {{ buf.line_style }}
#property indicator_width{{ loop.index }}  {{ buf.width }}
{% endfor %}

{% if levels %}
{% for lvl in levels %}
#property indicator_level{{ loop.index }} {{ lvl }}
{% endfor %}
{% endif %}

{% if minimum is not none %}
#property indicator_minimum {{ minimum }}
{% endif %}
{% if maximum is not none %}
#property indicator_maximum {{ maximum }}
{% endif %}

{% if inputs %}
//--- Input parameters
{{ inputs }}
{% endif %}

//--- Indicator buffers
{% for buf in buffers %}
double {{ buf.name }}Buffer[];
{% endfor %}

//+------------------------------------------------------------------+
//| Custom indicator initialization function                          |
//+------------------------------------------------------------------+
int OnInit()
{
{% for buf in buffers %}
   SetIndexBuffer({{ loop.index0 }}, {{ buf.name }}Buffer, INDICATOR_DATA);
   PlotIndexSetString({{ loop.index0 }}, PLOT_LABEL, "{{ buf.label or buf.name }}");
{% endfor %}

   IndicatorSetString(INDICATOR_SHORTNAME, "{{ short_name or name }}");
   IndicatorSetInteger(INDICATOR_DIGITS, _Digits);

{% if on_init_extra %}
   {{ on_init_extra }}
{% endif %}

   return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Custom indicator deinitialization function                        |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
{% if on_deinit_extra %}
   {{ on_deinit_extra }}
{% endif %}
}

//+------------------------------------------------------------------+
//| Custom indicator iteration function                               |
//+------------------------------------------------------------------+
int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < 2)
      return 0;

{{ on_calculate_body }}

   return rates_total;
}

{% if custom_functions %}
//+------------------------------------------------------------------+
//| Custom functions                                                  |
//+------------------------------------------------------------------+
{{ custom_functions }}
{% endif %}
//+------------------------------------------------------------------+
"""


# ---------------------------------------------------------------------------
# Built-in indicator presets
# ---------------------------------------------------------------------------

_MA_CALC = """\
   int start = (prev_calculated > 0) ? prev_calculated - 1 : InpMAPeriod;

   for(int i = start; i < rates_total; i++)
   {
      double sum = 0;
      for(int j = 0; j < InpMAPeriod && (i - j) >= 0; j++)
         sum += close[i - j];
      MABuffer[i] = sum / InpMAPeriod;
   }"""

_MA_INPUTS = """\
input int InpMAPeriod = 14;  // MA Period"""


_RSI_CALC = """\
   int start = (prev_calculated > 0) ? prev_calculated - 1 : InpRSIPeriod + 1;

   for(int i = start; i < rates_total; i++)
   {
      double gainSum = 0, lossSum = 0;
      for(int j = 1; j <= InpRSIPeriod && (i - j) >= 0; j++)
      {
         double change = close[i - j + 1] - close[i - j];
         if(change > 0) gainSum += change;
         else           lossSum += MathAbs(change);
      }
      double avgGain = gainSum / InpRSIPeriod;
      double avgLoss = lossSum / InpRSIPeriod;
      if(avgLoss == 0)
         RSIBuffer[i] = 100.0;
      else
         RSIBuffer[i] = 100.0 - (100.0 / (1.0 + avgGain / avgLoss));
   }"""

_RSI_INPUTS = """\
input int InpRSIPeriod = 14;  // RSI Period"""


_BB_CALC = """\
   int start = (prev_calculated > 0) ? prev_calculated - 1 : InpBBPeriod;

   for(int i = start; i < rates_total; i++)
   {
      double sum = 0;
      for(int j = 0; j < InpBBPeriod && (i - j) >= 0; j++)
         sum += close[i - j];
      double ma = sum / InpBBPeriod;

      double sumSq = 0;
      for(int j = 0; j < InpBBPeriod && (i - j) >= 0; j++)
         sumSq += MathPow(close[i - j] - ma, 2);
      double stddev = MathSqrt(sumSq / InpBBPeriod);

      MiddleBuffer[i] = ma;
      UpperBuffer[i]  = ma + InpBBDeviation * stddev;
      LowerBuffer[i]  = ma - InpBBDeviation * stddev;
   }"""

_BB_INPUTS = """\
input int    InpBBPeriod    = 20;   // BB Period
input double InpBBDeviation = 2.0;  // BB Deviation"""


_MACD_CALC = """\
   int start = (prev_calculated > 0) ? prev_calculated - 1 : InpSlowEMA;

   // Simple EMA approximation
   double fastK = 2.0 / (InpFastEMA + 1);
   double slowK = 2.0 / (InpSlowEMA + 1);
   double sigK  = 2.0 / (InpSignalSMA + 1);

   static double fastEMA = 0, slowEMA = 0, signalEMA = 0;
   if(prev_calculated == 0)
   {
      fastEMA = close[0]; slowEMA = close[0]; signalEMA = 0;
   }

   for(int i = start; i < rates_total; i++)
   {
      fastEMA = close[i] * fastK + fastEMA * (1 - fastK);
      slowEMA = close[i] * slowK + slowEMA * (1 - slowK);
      MACDBuffer[i] = fastEMA - slowEMA;
      signalEMA = MACDBuffer[i] * sigK + signalEMA * (1 - sigK);
      SignalBuffer[i] = signalEMA;
   }"""

_MACD_INPUTS = """\
input int InpFastEMA   = 12;  // Fast EMA Period
input int InpSlowEMA   = 26;  // Slow EMA Period
input int InpSignalSMA = 9;   // Signal SMA Period"""


_ATR_CALC = """\
   int start = (prev_calculated > 0) ? prev_calculated - 1 : InpATRPeriod + 1;

   for(int i = start; i < rates_total; i++)
   {
      double trSum = 0;
      for(int j = 0; j < InpATRPeriod && (i - j) >= 1; j++)
      {
         double tr = MathMax(high[i-j] - low[i-j],
                    MathMax(MathAbs(high[i-j] - close[i-j-1]),
                            MathAbs(low[i-j] - close[i-j-1])));
         trSum += tr;
      }
      ATRBuffer[i] = trSum / InpATRPeriod;
   }"""

_ATR_INPUTS = """\
input int InpATRPeriod = 14;  // ATR Period"""


_STOCH_CALC = """\
   int start = (prev_calculated > 0) ? prev_calculated - 1 : InpKPeriod;

   for(int i = start; i < rates_total; i++)
   {
      double highest = high[i], lowest = low[i];
      for(int j = 0; j < InpKPeriod && (i - j) >= 0; j++)
      {
         if(high[i-j] > highest) highest = high[i-j];
         if(low[i-j] < lowest)   lowest  = low[i-j];
      }
      if(highest - lowest > 0)
         KBuffer[i] = (close[i] - lowest) / (highest - lowest) * 100.0;
      else
         KBuffer[i] = 50.0;
   }

   // %D = SMA of %K
   for(int i = start; i < rates_total; i++)
   {
      double sum = 0;
      int cnt = 0;
      for(int j = 0; j < InpDPeriod && (i - j) >= 0; j++)
      {
         sum += KBuffer[i - j];
         cnt++;
      }
      DBuffer[i] = (cnt > 0) ? sum / cnt : 50.0;
   }"""

_STOCH_INPUTS = """\
input int InpKPeriod = 14;  // %K Period
input int InpDPeriod = 3;   // %D Period
input int InpSlowing = 3;   // Slowing"""


INDICATOR_PRESETS: Dict[IndicatorType, Dict[str, Any]] = {
    IndicatorType.MOVING_AVERAGE: {
        "buffers": [BufferSpec("MA", "Moving Average")],
        "inputs": _MA_INPUTS,
        "on_calculate_body": _MA_CALC,
        "window": "indicator_chart_window",
    },
    IndicatorType.RSI: {
        "buffers": [BufferSpec("RSI", "RSI", color="clrDodgerBlue")],
        "inputs": _RSI_INPUTS,
        "on_calculate_body": _RSI_CALC,
        "window": "indicator_separate_window",
        "levels": [30.0, 70.0],
        "minimum": 0.0,
        "maximum": 100.0,
    },
    IndicatorType.BOLLINGER_BANDS: {
        "buffers": [
            BufferSpec("Middle", "BB Middle", color="clrDodgerBlue"),
            BufferSpec("Upper", "BB Upper", color="clrRed"),
            BufferSpec("Lower", "BB Lower", color="clrRed"),
        ],
        "inputs": _BB_INPUTS,
        "on_calculate_body": _BB_CALC,
        "window": "indicator_chart_window",
    },
    IndicatorType.MACD: {
        "buffers": [
            BufferSpec("MACD", "MACD", style=DrawingStyle.HISTOGRAM, color="clrSilver"),
            BufferSpec("Signal", "Signal", color="clrRed"),
        ],
        "inputs": _MACD_INPUTS,
        "on_calculate_body": _MACD_CALC,
        "window": "indicator_separate_window",
        "levels": [0.0],
    },
    IndicatorType.ATR: {
        "buffers": [BufferSpec("ATR", "ATR", color="clrOrangeRed")],
        "inputs": _ATR_INPUTS,
        "on_calculate_body": _ATR_CALC,
        "window": "indicator_separate_window",
    },
    IndicatorType.STOCHASTIC: {
        "buffers": [
            BufferSpec("K", "%K", color="clrDodgerBlue"),
            BufferSpec("D", "%D", color="clrRed", line_style="STYLE_DOT"),
        ],
        "inputs": _STOCH_INPUTS,
        "on_calculate_body": _STOCH_CALC,
        "window": "indicator_separate_window",
        "levels": [20.0, 80.0],
        "minimum": 0.0,
        "maximum": 100.0,
    },
}


class IndicatorGenerator:
    """Generates MQL5 custom indicator source files."""

    def __init__(self) -> None:
        self._env = Environment(
            loader=BaseLoader(),
            keep_trailing_newline=True,
            trim_blocks=True,
            lstrip_blocks=True,
        )
        self._template = self._env.from_string(_INDICATOR_TEMPLATE)

    def generate(self, config: IndicatorConfig) -> str:
        """Render the indicator template with the given configuration."""
        ctx = self._build_context(config)
        return self._template.render(**ctx)

    def generate_to_file(self, config: IndicatorConfig, output_path: Path) -> Path:
        """Generate indicator and write the .mq5 file."""
        code = self.generate(config)
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(code, encoding="utf-8")
        logger.info("Indicator written to %s (%d bytes)", output_path, len(code))
        return output_path

    def generate_preset(self, indicator_type: IndicatorType, name: Optional[str] = None) -> str:
        """Generate a preset indicator by type."""
        preset = INDICATOR_PRESETS.get(indicator_type)
        if not preset:
            raise ValueError(f"No preset for indicator type: {indicator_type}")

        config = IndicatorConfig(
            name=name or f"JARVIS_{indicator_type.value}",
            indicator_type=indicator_type,
            buffers=preset["buffers"],
            inputs=preset.get("inputs", ""),
            window=preset.get("window", "indicator_chart_window"),
            on_calculate_body=preset.get("on_calculate_body", ""),
            levels=preset.get("levels", []),
            minimum=preset.get("minimum"),
            maximum=preset.get("maximum"),
        )
        return self.generate(config)

    def list_indicator_types(self) -> List[str]:
        """Return available indicator type names."""
        return [t.value for t in IndicatorType]

    def _build_context(self, config: IndicatorConfig) -> Dict[str, Any]:
        preset = INDICATOR_PRESETS.get(config.indicator_type, {})

        buffers = config.buffers or preset.get("buffers", [])
        if not buffers:
            buffers = [BufferSpec("Value", config.name)]

        return {
            "name": config.name,
            "short_name": config.short_name or config.name,
            "window": config.window or preset.get("window", "indicator_chart_window"),
            "buffers": buffers,
            "buffer_count": len(buffers),
            "plot_count": len(buffers),
            "inputs": config.inputs or preset.get("inputs", ""),
            "on_init_extra": config.on_init_extra,
            "on_deinit_extra": config.on_deinit_extra,
            "on_calculate_body": config.on_calculate_body or preset.get("on_calculate_body", ""),
            "custom_functions": config.custom_functions,
            "levels": config.levels if config.levels else preset.get("levels", []),
            "minimum": config.minimum if config.minimum is not None else preset.get("minimum"),
            "maximum": config.maximum if config.maximum is not None else preset.get("maximum"),
        }
