"""SQLAlchemy ORM models for the JARVIS Trading OS.

All models inherit from the shared ``Base`` and follow a consistent pattern:
auto-incrementing primary key, created/updated timestamps where appropriate,
and explicit ``__tablename__`` declarations.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Optional

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# Strategy
# ---------------------------------------------------------------------------


class Strategy(Base):
    """A trading strategy definition with aggregated performance stats."""

    __tablename__ = "strategies"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(String(128), unique=True, nullable=False, index=True)
    type: Mapped[str] = mapped_column(String(64), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    parameters: Mapped[Optional[dict[str, Any]]] = mapped_column(JSON, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    winrate: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    profit_factor: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    total_trades: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, server_default=func.now(), nullable=False,
    )

    trades: Mapped[list["Trade"]] = relationship("Trade", back_populates="strategy", lazy="selectin")
    signals: Mapped[list["Signal"]] = relationship("Signal", back_populates="strategy", lazy="selectin")
    bot_configs: Mapped[list["BotConfig"]] = relationship("BotConfig", back_populates="strategy", lazy="selectin")

    def __repr__(self) -> str:
        return f"<Strategy id={self.id} name={self.name!r}>"


# ---------------------------------------------------------------------------
# Trade
# ---------------------------------------------------------------------------


class Trade(Base):
    """An individual trade (open or closed)."""

    __tablename__ = "trades"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    direction: Mapped[str] = mapped_column(String(8), nullable=False)  # "buy" | "sell"
    volume: Mapped[float] = mapped_column(Float, nullable=False)
    open_price: Mapped[float] = mapped_column(Float, nullable=False)
    close_price: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    sl: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    tp: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    open_time: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, nullable=False,
    )
    close_time: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    profit: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    status: Mapped[str] = mapped_column(
        String(16), default="open", nullable=False, index=True,
    )  # "open" | "closed" | "cancelled"
    strategy_name: Mapped[Optional[str]] = mapped_column(String(128), nullable=True)
    strategy_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("strategies.id"), nullable=True,
    )

    strategy: Mapped[Optional["Strategy"]] = relationship("Strategy", back_populates="trades")

    def __repr__(self) -> str:
        return f"<Trade id={self.id} {self.symbol} {self.direction} status={self.status}>"


# ---------------------------------------------------------------------------
# Signal
# ---------------------------------------------------------------------------


class Signal(Base):
    """A trading signal generated by a strategy or external source."""

    __tablename__ = "signals"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    direction: Mapped[str] = mapped_column(String(8), nullable=False)
    strategy_name: Mapped[str] = mapped_column(String(128), nullable=False)
    strategy_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("strategies.id"), nullable=True,
    )
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    timeframe: Mapped[str] = mapped_column(String(8), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, server_default=func.now(), nullable=False,
    )
    executed: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    strategy: Mapped[Optional["Strategy"]] = relationship("Strategy", back_populates="signals")

    def __repr__(self) -> str:
        return f"<Signal id={self.id} {self.symbol} {self.direction} conf={self.confidence}>"


# ---------------------------------------------------------------------------
# AccountSnapshot
# ---------------------------------------------------------------------------


class AccountSnapshot(Base):
    """Point-in-time snapshot of the trading account metrics."""

    __tablename__ = "account_snapshots"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    balance: Mapped[float] = mapped_column(Float, nullable=False)
    equity: Mapped[float] = mapped_column(Float, nullable=False)
    margin: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    free_margin: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    drawdown: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, server_default=func.now(), nullable=False, index=True,
    )

    def __repr__(self) -> str:
        return f"<AccountSnapshot id={self.id} balance={self.balance}>"


# ---------------------------------------------------------------------------
# ChatMessage
# ---------------------------------------------------------------------------


class ChatMessage(Base):
    """A single message in the AI chat history."""

    __tablename__ = "chat_messages"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    role: Mapped[str] = mapped_column(String(16), nullable=False)  # "user" | "assistant" | "system"
    content: Mapped[str] = mapped_column(Text, nullable=False)
    metadata_json: Mapped[Optional[dict[str, Any]]] = mapped_column(
        "metadata", JSON, nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, server_default=func.now(), nullable=False,
    )

    def __repr__(self) -> str:
        return f"<ChatMessage id={self.id} role={self.role!r}>"


# ---------------------------------------------------------------------------
# BotConfig
# ---------------------------------------------------------------------------


class BotConfig(Base):
    """Configuration record for an automated trading bot instance."""

    __tablename__ = "bot_configs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(String(128), unique=True, nullable=False)
    strategy_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("strategies.id"), nullable=True,
    )
    symbol: Mapped[str] = mapped_column(String(32), nullable=False)
    timeframe: Mapped[str] = mapped_column(String(8), nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    parameters: Mapped[Optional[dict[str, Any]]] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, server_default=func.now(), nullable=False,
    )

    strategy: Mapped[Optional["Strategy"]] = relationship("Strategy", back_populates="bot_configs")

    def __repr__(self) -> str:
        return f"<BotConfig id={self.id} name={self.name!r}>"
