from pathlib import Path


class MQL5Generator:
    def __init__(self, base_dir: Path) -> None:
        self.base_dir = base_dir
        self.base_dir.mkdir(parents=True, exist_ok=True)

    def generate_expert_advisor(self, bot_name: str, strategy_logic: str) -> Path:
        file_name = f"{bot_name}.mq5"
        target_file = self.base_dir / file_name
        content = self._render_template(bot_name=bot_name, strategy_logic=strategy_logic)
        target_file.write_text(content, encoding="utf-8")
        return target_file

    def _render_template(self, bot_name: str, strategy_logic: str) -> str:
        return f"""#property strict
#property version   "1.00"
#property description "Auto generated by JARVIS"

input double RiskPercent = 1.0;

int OnInit()
{{
   Print("{bot_name} initialized");
   return(INIT_SUCCEEDED);
}}

void OnTick()
{{
   {strategy_logic}
}}
"""
