"""Generate MQL5 Expert Advisor and indicator skeletons from high-level specs."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class ExpertSpec:
    name: str
    symbol: str
    magic: int = 900001
    comment: str = "JARVIS"


class MQL5Generator:
    def expert_advisor(self, spec: ExpertSpec) -> str:
        safe_name = "".join(c for c in spec.name if c.isalnum() or c == "_") or "JarvisEA"
        return f"""//+------------------------------------------------------------------+
//| {safe_name}.mq5                                                  |
//| Generated by JARVIS — review before live trading                 |
//+------------------------------------------------------------------+
#property strict
#property copyright "JARVIS"
#property version   "1.00"

#include <Trade\\Trade.mqh>

CTrade trade;
input int InpMagic = {spec.magic};
input double InpLots = 0.1;
input int InpSlippage = 10;

int OnInit()
  {{
   trade.SetExpertMagicNumber(InpMagic);
   trade.SetDeviationInPoints(InpSlippage);
   return(INIT_SUCCEEDED);
  }}

void OnDeinit(const int reason) {{}}

void OnTick()
  {{
   // TODO: connect to JARVIS signals / risk engine via file or socket bridge
   // Default: no-op scaffold for {spec.symbol}
  }}
"""

    def custom_indicator(self, name: str) -> str:
        safe = "".join(c for c in name if c.isalnum() or c == "_") or "JarvisInd"
        return f"""//+------------------------------------------------------------------+
//| {safe}.mq5                                                       |
//+------------------------------------------------------------------+
#property indicator_chart_window
#property indicator_buffers 1
#property indicator_plots   1

double BufferMA[];

int OnInit()
  {{
   SetIndexBuffer(0, BufferMA, INDICATOR_DATA);
   PlotIndexSetString(0, PLOT_LABEL, "{safe}");
   return(INIT_SUCCEEDED);
  }}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
  {{
   // TODO: implement logic
   return(rates_total);
  }}
"""


def build_expert_from_prompt(prompt: str) -> ExpertSpec:
    """Very small heuristic mapper — replace with LLM-structured output later."""
    symbol = "XAUUSD"
    lowered = prompt.lower()
    if "gold" in lowered or "xau" in lowered:
        symbol = "XAUUSD"
    elif "eur" in lowered:
        symbol = "EURUSD"
    name = "JarvisEA_" + symbol
    return ExpertSpec(name=name, symbol=symbol)
