"""
MQL5 Service - generates Expert Advisors and indicators, manages file install to MT5.
"""
import logging
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from app.core.config import settings

logger = logging.getLogger(__name__)


def _ea_template(
    name: str,
    strategy_type: str,
    description: str,
    symbols: List[str],
    timeframes: List[str],
    risk_percent: float,
    max_trades: int,
    use_trailing_stop: bool,
    indicators: List[str],
) -> str:
    symbols_str = ", ".join(symbols) if symbols else "Any"
    tf_str = ", ".join(timeframes) if timeframes else "Any"
    ind_str = ", ".join(indicators) if indicators else "None"
    ts_code = """
   // Trailing Stop
   if(useTrailingStop && pos.PositionGetInteger(POSITION_MAGIC) == MagicNumber) {
      double sl = pos.PositionGetDouble(POSITION_SL);
      double price = pos.PositionGetDouble(POSITION_PRICE_CURRENT);
      double open  = pos.PositionGetDouble(POSITION_PRICE_OPEN);
      ENUM_POSITION_TYPE type = (ENUM_POSITION_TYPE)pos.PositionGetInteger(POSITION_TYPE);
      double trail = TrailingStopPips * _Point * 10;
      if(type == POSITION_TYPE_BUY && price - open > trail) {
         double new_sl = NormalizeDouble(price - trail, _Digits);
         if(new_sl > sl) trade.PositionModify(pos.PositionGetInteger(POSITION_TICKET), new_sl, pos.PositionGetDouble(POSITION_TP));
      }
      if(type == POSITION_TYPE_SELL && open - price > trail) {
         double new_sl = NormalizeDouble(price + trail, _Digits);
         if(new_sl < sl || sl == 0) trade.PositionModify(pos.PositionGetInteger(POSITION_TICKET), new_sl, pos.PositionGetDouble(POSITION_TP));
      }
   }""" if use_trailing_stop else ""

    return f"""//+------------------------------------------------------------------+
//| {name}.mq5                                                       |
//| Generated by JARVIS AI Trading OS                                |
//| Strategy: {strategy_type}                                        |
//| Symbols: {symbols_str}                                           |
//| Timeframes: {tf_str}                                             |
//| Description: {description}                                       |
//| Indicators: {ind_str}                                            |
//+------------------------------------------------------------------+
#property copyright "JARVIS AI Trading OS"
#property link      "https://jarvis-trading.ai"
#property version   "1.00"
#property strict

#include <Trade\\Trade.mqh>
#include <Trade\\PositionInfo.mqh>
#include <Trade\\AccountInfo.mqh>

//--- Input Parameters
input double RiskPercent       = {risk_percent};  // Risk % per trade
input double StopLossPips      = 30.0;            // Stop Loss in pips
input double TakeProfitPips    = 60.0;            // Take Profit in pips
input int    MagicNumber       = 12345;           // Magic number
input int    MaxOpenTrades     = {max_trades};    // Max simultaneous trades
input bool   useTrailingStop   = {"true" if use_trailing_stop else "false"};  // Enable trailing stop
input double TrailingStopPips  = 15.0;            // Trailing stop in pips
input int    FastMAPeriod      = 9;               // Fast MA period
input int    SlowMAPeriod      = 21;              // Slow MA period
input int    RSIPeriod         = 14;              // RSI period
input int    RSIOverbought     = 70;              // RSI overbought level
input int    RSIOversold       = 30;              // RSI oversold level
input string TradeComment      = "JARVIS-{name[:10]}"; // Trade comment

//--- Global Variables
CTrade  trade;
CPositionInfo pos;
CAccountInfo  account;
int     hFastMA, hSlowMA, hRSI;
datetime lastBarTime = 0;
int openTradesCount  = 0;

//+------------------------------------------------------------------+
int OnInit() {{
   trade.SetExpertMagicNumber(MagicNumber);
   trade.SetDeviationInPoints(10);
   trade.SetTypeFilling(ORDER_FILLING_IOC);

   hFastMA = iMA(_Symbol, PERIOD_CURRENT, FastMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   hSlowMA = iMA(_Symbol, PERIOD_CURRENT, SlowMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   hRSI    = iRSI(_Symbol, PERIOD_CURRENT, RSIPeriod, PRICE_CLOSE);

   if(hFastMA == INVALID_HANDLE || hSlowMA == INVALID_HANDLE || hRSI == INVALID_HANDLE) {{
      Print("ERROR: Failed to create indicator handles");
      return INIT_FAILED;
   }}
   Print("{name} initialized on ", _Symbol, " ", EnumToString(Period()));
   return INIT_SUCCEEDED;
}}

//+------------------------------------------------------------------+
void OnDeinit(const int reason) {{
   IndicatorRelease(hFastMA);
   IndicatorRelease(hSlowMA);
   IndicatorRelease(hRSI);
   Print("{name} removed. Reason: ", reason);
}}

//+------------------------------------------------------------------+
void OnTick() {{
   // Only process on new bar
   datetime barTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(barTime == lastBarTime) return;
   lastBarTime = barTime;

   if(!IsMarketOpen()) return;
   if(!CheckDailyLossLimit()) return;

   // Count open positions
   openTradesCount = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
      if(pos.SelectByIndex(i) && pos.Magic() == MagicNumber && pos.Symbol() == _Symbol)
         openTradesCount++;

   // Read indicator values
   double fastMA[2], slowMA[2], rsiVal[2];
   if(CopyBuffer(hFastMA, 0, 0, 2, fastMA) < 2) return;
   if(CopyBuffer(hSlowMA, 0, 0, 2, slowMA) < 2) return;
   if(CopyBuffer(hRSI,    0, 0, 2, rsiVal) < 2) return;

   bool bullCross = fastMA[0] > slowMA[0] && fastMA[1] <= slowMA[1];
   bool bearCross = fastMA[0] < slowMA[0] && fastMA[1] >= slowMA[1];
   bool rsiBull   = rsiVal[0] < RSIOverbought;
   bool rsiBear   = rsiVal[0] > RSIOversold;

   if(openTradesCount < MaxOpenTrades) {{
      if(bullCross && rsiBull) ExecuteTrade(ORDER_TYPE_BUY);
      if(bearCross && rsiBear) ExecuteTrade(ORDER_TYPE_SELL);
   }}

   // Manage existing positions
   ManagePositions();
}}

//+------------------------------------------------------------------+
void ExecuteTrade(ENUM_ORDER_TYPE type) {{
   MqlTick tick;
   if(!SymbolInfoTick(_Symbol, tick)) return;

   double price  = (type == ORDER_TYPE_BUY) ? tick.ask : tick.bid;
   double pipVal = _Point * ((_Digits == 5 || _Digits == 3) ? 10.0 : 1.0);
   double sl     = (type == ORDER_TYPE_BUY) ? price - StopLossPips * pipVal : price + StopLossPips * pipVal;
   double tp     = (type == ORDER_TYPE_BUY) ? price + TakeProfitPips * pipVal : price - TakeProfitPips * pipVal;
   double lots   = CalculateLotSize(StopLossPips * pipVal);
   if(lots <= 0) return;

   sl = NormalizeDouble(sl, _Digits);
   tp = NormalizeDouble(tp, _Digits);

   if(trade.PositionOpen(_Symbol, type, lots, price, sl, tp, TradeComment))
      Print("Trade opened: ", EnumToString(type), " ", lots, " lots @ ", price);
   else
      Print("Trade failed: ", trade.ResultRetcodeDescription());
}}

//+------------------------------------------------------------------+
double CalculateLotSize(double slDistance) {{
   if(slDistance <= 0) return 0;
   double accountBalance = account.Balance();
   double riskAmount     = accountBalance * RiskPercent / 100.0;
   double tickValue      = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize       = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double lotStep        = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   double minLot         = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot         = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);

   if(tickValue <= 0 || tickSize <= 0) return minLot;
   double pipValue = tickValue / tickSize * slDistance;
   double lots     = riskAmount / pipValue;
   lots = MathFloor(lots / lotStep) * lotStep;
   return MathMax(minLot, MathMin(maxLot, lots));
}}

//+------------------------------------------------------------------+
void ManagePositions() {{{ts_code}
}}

//+------------------------------------------------------------------+
bool IsMarketOpen() {{
   MqlDateTime dt;
   TimeToStruct(TimeCurrent(), dt);
   if(dt.day_of_week == 0 || dt.day_of_week == 6) return false;
   return true;
}}

//+------------------------------------------------------------------+
bool CheckDailyLossLimit() {{
   static datetime lastDay = 0;
   static double   dayStartBalance = 0;
   MqlDateTime dt;
   TimeToStruct(TimeCurrent(), dt);
   datetime today = StringToTime(IntegerToString(dt.year) + "." + IntegerToString(dt.mon) + "." + IntegerToString(dt.day));
   if(today != lastDay) {{
      lastDay = today;
      dayStartBalance = account.Balance();
   }}
   double currentEquity = account.Equity();
   double dailyLossPct  = (dayStartBalance - currentEquity) / dayStartBalance * 100.0;
   if(dailyLossPct >= 5.0) {{
      Print("DAILY LOSS LIMIT REACHED (", dailyLossPct, "%). Trading halted for today.");
      return false;
   }}
   return true;
}}

//+------------------------------------------------------------------+
void OnTradeTransaction(const MqlTradeTransaction &trans, const MqlTradeRequest &request, const MqlTradeResult &result) {{
   if(trans.type == TRADE_TRANSACTION_DEAL_ADD) {{
      if(trans.deal_type == DEAL_TYPE_BUY || trans.deal_type == DEAL_TYPE_SELL)
         Print("New deal: #", trans.deal, " ", EnumToString(trans.deal_type), " volume=", trans.volume, " price=", trans.price);
   }}
}}
//+------------------------------------------------------------------+
"""


def _indicator_template(name: str, description: str) -> str:
    return f"""//+------------------------------------------------------------------+
//| {name}.mq5                                                       |
//| Generated by JARVIS AI Trading OS                                |
//| Description: {description}                                       |
//+------------------------------------------------------------------+
#property copyright "JARVIS AI Trading OS"
#property link      "https://jarvis-trading.ai"
#property version   "1.00"
#property indicator_chart_window
#property indicator_buffers 2
#property indicator_plots   2
#property indicator_label1  "Fast MA"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrBlue
#property indicator_width1  2
#property indicator_label2  "Slow MA"
#property indicator_type2   DRAW_LINE
#property indicator_color2  clrOrange
#property indicator_width2  2

input int FastPeriod = 9;
input int SlowPeriod = 21;

double FastMABuffer[];
double SlowMABuffer[];
int hFastMA, hSlowMA;

int OnInit() {{
   SetIndexBuffer(0, FastMABuffer, INDICATOR_DATA);
   SetIndexBuffer(1, SlowMABuffer, INDICATOR_DATA);
   hFastMA = iMA(_Symbol, PERIOD_CURRENT, FastPeriod, 0, MODE_EMA, PRICE_CLOSE);
   hSlowMA = iMA(_Symbol, PERIOD_CURRENT, SlowPeriod, 0, MODE_EMA, PRICE_CLOSE);
   IndicatorSetString(INDICATOR_SHORTNAME, "{name[:8]}");
   return INIT_SUCCEEDED;
}}

int OnCalculate(const int rates_total, const int prev_calculated,
                const datetime &time[], const double &open[],
                const double &high[], const double &low[],
                const double &close[], const long &tick_volume[],
                const long &volume[], const int &spread[]) {{
   if(rates_total < SlowPeriod + 1) return 0;
   int start = (prev_calculated > 0) ? prev_calculated - 1 : SlowPeriod;
   double fastBuf[1], slowBuf[1];
   for(int i = start; i < rates_total; i++) {{
      if(CopyBuffer(hFastMA, 0, rates_total - 1 - i, 1, fastBuf) > 0) FastMABuffer[i] = fastBuf[0];
      if(CopyBuffer(hSlowMA, 0, rates_total - 1 - i, 1, slowBuf) > 0) SlowMABuffer[i] = slowBuf[0];
   }}
   return rates_total;
}}
//+------------------------------------------------------------------+
"""


class MQL5Service:

    experts_dir = Path(settings.GENERATED_FILES_DIR) / "mql5" / "experts"
    indicators_dir = Path(settings.GENERATED_FILES_DIR) / "mql5" / "indicators"

    @classmethod
    def _ensure_dirs(cls) -> None:
        cls.experts_dir.mkdir(parents=True, exist_ok=True)
        cls.indicators_dir.mkdir(parents=True, exist_ok=True)

    @classmethod
    def generate_ea(
        cls,
        name: str,
        strategy_type: str,
        description: str,
        symbols: List[str],
        timeframes: List[str],
        risk_percent: float = 2.0,
        max_trades: int = 1,
        use_trailing_stop: bool = True,
        indicators: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        cls._ensure_dirs()
        code = _ea_template(
            name, strategy_type, description, symbols, timeframes,
            risk_percent, max_trades, use_trailing_stop, indicators or []
        )
        filename = f"{name.replace(' ', '_')}.mq5"
        file_path = cls.experts_dir / filename
        file_path.write_text(code, encoding="utf-8")
        return {
            "filename": filename,
            "path": str(file_path),
            "type": "EA",
            "size": len(code),
            "created_at": datetime.utcnow().isoformat(),
        }

    @classmethod
    def generate_indicator(cls, name: str, description: str) -> Dict[str, Any]:
        cls._ensure_dirs()
        code = _indicator_template(name, description)
        filename = f"{name.replace(' ', '_')}.mq5"
        file_path = cls.indicators_dir / filename
        file_path.write_text(code, encoding="utf-8")
        return {
            "filename": filename,
            "path": str(file_path),
            "type": "Indicator",
            "size": len(code),
            "created_at": datetime.utcnow().isoformat(),
        }

    @classmethod
    def list_files(cls, file_type: Optional[str] = None) -> List[Dict[str, Any]]:
        cls._ensure_dirs()
        files = []
        dirs = []
        if not file_type or file_type == "ea":
            dirs.append(("EA", cls.experts_dir))
        if not file_type or file_type == "indicator":
            dirs.append(("Indicator", cls.indicators_dir))
        for ftype, d in dirs:
            for f in d.glob("*.mq5"):
                stat = f.stat()
                files.append({
                    "filename": f.name,
                    "type": ftype,
                    "path": str(f),
                    "size": stat.st_size,
                    "modified_at": datetime.fromtimestamp(stat.st_mtime).isoformat(),
                })
        return files

    @classmethod
    def read_file(cls, filename: str) -> str:
        for d in [cls.experts_dir, cls.indicators_dir]:
            p = d / filename
            if p.exists():
                return p.read_text(encoding="utf-8")
        raise FileNotFoundError(f"File not found: {filename}")

    @classmethod
    def install_to_mt5(cls, filename: str) -> Dict[str, Any]:
        for ftype, src_dir, dest_setting in [
            ("EA", cls.experts_dir, settings.MT5_EXPERTS_PATH),
            ("Indicator", cls.indicators_dir, settings.MT5_INDICATORS_PATH),
        ]:
            src = src_dir / filename
            if src.exists():
                dest_dir = Path(dest_setting)
                if not dest_dir.exists():
                    return {
                        "success": False,
                        "message": f"MT5 {ftype} path not found: {dest_dir}",
                        "filename": filename,
                    }
                dest = dest_dir / filename
                shutil.copy2(src, dest)
                return {"success": True, "message": f"Installed {ftype} to {dest}", "filename": filename, "type": ftype}
        raise FileNotFoundError(f"File not found: {filename}")

    @classmethod
    def install_all(cls) -> Dict[str, Any]:
        results = []
        for f in cls.list_files():
            try:
                r = cls.install_to_mt5(f["filename"])
                results.append(r)
            except Exception as exc:
                results.append({"success": False, "filename": f["filename"], "error": str(exc)})
        return {"installed": sum(1 for r in results if r.get("success")), "total": len(results), "results": results}

    @classmethod
    def list_mt5_files(cls, file_type: str = "experts") -> List[Dict[str, Any]]:
        path = Path(settings.MT5_EXPERTS_PATH if file_type == "experts" else settings.MT5_INDICATORS_PATH)
        if not path.exists():
            return []
        return [
            {
                "filename": f.name,
                "path": str(f),
                "size": f.stat().st_size,
                "modified_at": datetime.fromtimestamp(f.stat().st_mtime).isoformat(),
            }
            for f in path.glob("*.mq5")
            if f.is_file()
        ]
