from pathlib import Path

from app.core.config import settings
from app.models.schemas import ChatRequest, ChatResponse
from app.services.backtesting_engine import BacktestingEngine
from app.services.file_generator import FileGenerator
from app.services.mql5_generator import MQL5Generator
from app.services.mt5_connector import MT5Connector
from app.services.risk_engine import RiskEngine
from app.services.strategy_registry import StrategyRegistry
from app.services.telegram_service import TelegramService
from app.services.tradingview_service import TradingViewService


class JarvisOrchestrator:
    def __init__(self) -> None:
        workspace_root = Path(__file__).resolve().parents[3]
        self.mt5 = MT5Connector()
        self.risk_engine = RiskEngine(max_loss_threshold_pct=20.0)
        self.backtesting = BacktestingEngine()
        self.strategy_registry = StrategyRegistry()
        self.file_generator = FileGenerator(workspace_root=workspace_root)
        self.mql5_generator = MQL5Generator(
            templates_dir=workspace_root / "mql5" / "templates",
            output_dir=workspace_root / "mql5" / "generated",
        )
        self.telegram = TelegramService(settings.telegram_token, settings.telegram_chat_id)
        self.tradingview = TradingViewService()

    def process_chat_command(self, request: ChatRequest) -> ChatResponse:
        command = request.command.lower().strip()
        actions: list[str] = []
        generated_files: list[str] = []

        if "gold-scalping-bot" in command or "gold scalping bot" in command:
            strategy_code = self._build_strategy_template("gold_scalping_core")
            strategy_path = self.file_generator.create_strategy_module(
                "gold_scalping_core",
                strategy_code,
            )
            generated_files.append(str(strategy_path))
            actions.append("Created Python strategy module for gold scalping.")

            mq5_path = self.mql5_generator.generate_expert_advisor(
                bot_name="JarvisGoldScalper",
                symbol="XAUUSD",
                timeframe="M5",
                strategy_description="AI-assisted gold scalping strategy with risk controls.",
            )
            generated_files.append(str(mq5_path))
            actions.append("Generated MQL5 expert advisor template.")

        if "ict" in command:
            strategy_code = self._build_strategy_template("ict_liquidity_sweep")
            strategy_path = self.file_generator.create_strategy_module(
                "ict_liquidity_sweep",
                strategy_code,
            )
            generated_files.append(str(strategy_path))
            actions.append("Created ICT strategy scaffold.")

        if "news-filter" in command or "news filter" in command:
            module_path = self.file_generator.create_python_module(
                "backend/app/services/news_filter.py",
                self._news_filter_template(),
            )
            generated_files.append(str(module_path))
            actions.append("Created news filter service module.")

        if "telegram-signal-bot" in command or "telegram signal bot" in command:
            module_path = self.file_generator.create_python_module(
                "telegram/signal_bot_plan.md",
                "# Telegram Signal Bot Plan\n\n- Signal formatting\n- Routing\n- Alert priorities\n",
            )
            generated_files.append(str(module_path))
            actions.append("Prepared Telegram signal bot blueprint.")

        if "trailing stop" in command:
            module_path = self.file_generator.create_python_module(
                "risk_management/trailing_stop_policy.yaml",
                "mode: dynamic\natr_multiplier: 1.8\nbreak_even_buffer_pips: 4\n",
            )
            generated_files.append(str(module_path))
            actions.append("Added trailing stop risk policy.")

        if not actions:
            actions.append("Command understood. No files changed; ready for next detailed instruction.")

        return ChatResponse(
            summary="JARVIS command processed.",
            actions=actions,
            generated_files=generated_files,
        )

    @staticmethod
    def _build_strategy_template(strategy_name: str) -> str:
        return f'''"""
Strategy module: {strategy_name}
Generated by JARVIS file generator.
"""

from dataclasses import dataclass


@dataclass
class Signal:
    action: str
    confidence: float


def evaluate(context: dict) -> Signal:
    # Replace with production-grade feature engineering and signal logic.
    return Signal(action="hold", confidence=0.5)
'''

    @staticmethod
    def _news_filter_template() -> str:
        return '''from datetime import datetime, timedelta


class NewsFilter:
    def __init__(self, cooldown_minutes: int = 30) -> None:
        self.cooldown = timedelta(minutes=cooldown_minutes)
        self.last_high_impact_event: datetime | None = None

    def block_trading(self, now: datetime) -> bool:
        if self.last_high_impact_event is None:
            return False
        return now - self.last_high_impact_event <= self.cooldown
'''
