"""
TradingView Service - processes webhook signals and generates Pine Script.
"""
import hashlib
import hmac
import json
import logging
from datetime import datetime
from typing import Any, Dict, List, Optional

from sqlalchemy.orm import Session

from app.models.tradingview_model import TradingViewConfig, TradingViewSignal

logger = logging.getLogger(__name__)


class TradingViewService:

    @staticmethod
    def save_config(db: Session, webhook_secret: str) -> TradingViewConfig:
        existing = db.query(TradingViewConfig).first()
        if existing:
            existing.webhook_secret = webhook_secret
            existing.updated_at = datetime.utcnow()
            db.commit()
            db.refresh(existing)
            return existing
        config = TradingViewConfig(webhook_secret=webhook_secret, is_active=True)
        db.add(config)
        db.commit()
        db.refresh(config)
        return config

    @staticmethod
    def get_config(db: Session) -> Optional[TradingViewConfig]:
        return db.query(TradingViewConfig).filter(TradingViewConfig.is_active == True).first()  # noqa: E712

    @staticmethod
    def get_status(db: Session) -> Dict[str, Any]:
        config = TradingViewService.get_config(db)
        count = db.query(TradingViewSignal).count()
        pending = db.query(TradingViewSignal).filter(TradingViewSignal.processed == False).count()  # noqa: E712
        return {
            "configured": config is not None,
            "webhook_secret_set": bool(config and config.webhook_secret),
            "total_signals": count,
            "pending_signals": pending,
            "webhook_url": "/api/tradingview/webhook",
        }

    @staticmethod
    def verify_signature(payload: bytes, signature: str, secret: str) -> bool:
        """Verify HMAC-SHA256 signature from TradingView."""
        expected = hmac.new(secret.encode(), payload, hashlib.sha256).hexdigest()
        return hmac.compare_digest(expected, signature)

    @staticmethod
    def parse_and_save_signal(db: Session, payload: Dict[str, Any]) -> TradingViewSignal:
        signal = TradingViewSignal(
            ticker=payload.get("ticker", payload.get("symbol", "UNKNOWN")),
            action=str(payload.get("action", payload.get("side", "BUY"))).upper(),
            order_type=payload.get("order_type", "MARKET"),
            price=payload.get("price"),
            quantity=payload.get("quantity", payload.get("qty")),
            stop_loss=payload.get("stop_loss", payload.get("sl")),
            take_profit=payload.get("take_profit", payload.get("tp")),
            comment=payload.get("comment", "TradingView Signal"),
            raw_payload=payload,
            processed=False,
        )
        db.add(signal)
        db.commit()
        db.refresh(signal)
        logger.info("Saved TradingView signal #%d: %s %s", signal.id, signal.action, signal.ticker)
        return signal

    @staticmethod
    def get_signals(
        db: Session,
        skip: int = 0,
        limit: int = 50,
        processed: Optional[bool] = None,
    ) -> List[TradingViewSignal]:
        q = db.query(TradingViewSignal).order_by(TradingViewSignal.created_at.desc())
        if processed is not None:
            q = q.filter(TradingViewSignal.processed == processed)
        return q.offset(skip).limit(limit).all()

    @staticmethod
    def mark_processed(db: Session, signal_id: int, ticket: Optional[int] = None, error: Optional[str] = None) -> None:
        signal = db.query(TradingViewSignal).filter(TradingViewSignal.id == signal_id).first()
        if signal:
            signal.processed = True
            signal.processed_at = datetime.utcnow()
            if ticket:
                signal.trade_ticket = ticket
            if error:
                signal.error = error
            db.commit()

    @staticmethod
    def generate_pinescript_template(
        name: str,
        description: str,
        strategy_type: Optional[str] = None,
    ) -> str:
        """Generate a basic Pine Script v5 template (AI generation augments this)."""
        return f"""//@version=5
// {name}
// {description}
// Generated by JARVIS AI Trading OS
// Strategy type: {strategy_type or "Custom"}

indicator(title="{name}", shorttitle="{name[:6]}", overlay=true)

// ─── Inputs ───────────────────────────────────────────────────────────────
fast_length = input.int(9, title="Fast MA Length", minval=1)
slow_length = input.int(21, title="Slow MA Length", minval=1)
rsi_length = input.int(14, title="RSI Length", minval=1)
rsi_overbought = input.int(70, title="RSI Overbought", minval=50, maxval=100)
rsi_oversold = input.int(30, title="RSI Oversold", minval=0, maxval=50)

// ─── Calculations ─────────────────────────────────────────────────────────
fast_ma = ta.ema(close, fast_length)
slow_ma = ta.ema(close, slow_length)
rsi = ta.rsi(close, rsi_length)

bull_cross = ta.crossover(fast_ma, slow_ma)
bear_cross = ta.crossunder(fast_ma, slow_ma)

long_signal  = bull_cross and rsi < rsi_overbought
short_signal = bear_cross and rsi > rsi_oversold

// ─── Plots ────────────────────────────────────────────────────────────────
plot(fast_ma, title="Fast MA", color=color.blue, linewidth=1)
plot(slow_ma, title="Slow MA", color=color.orange, linewidth=1)

plotshape(long_signal,  title="Long",  style=shape.triangleup,   location=location.belowbar, color=color.green, size=size.small)
plotshape(short_signal, title="Short", style=shape.triangledown, location=location.abovebar, color=color.red,   size=size.small)

// ─── Alerts ───────────────────────────────────────────────────────────────
alertcondition(long_signal,  title="Long Signal",  message='{{"ticker":"{{ticker}}","action":"BUY","price":{{close}}}}')
alertcondition(short_signal, title="Short Signal", message='{{"ticker":"{{ticker}}","action":"SELL","price":{{close}}}}')
"""
