"""
J.A.R.V.I.S. V300 - CODE GENERATION ENGINE
Generates, validates, and deploys Python applications
into the /apps directory with automatic quality checks.
"""
import ast
import importlib
import logging
import os
import subprocess
import sys
import textwrap
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

logger = logging.getLogger("JARVIS.Coder")


@dataclass
class CodeTemplate:
    name: str
    description: str
    template: str
    category: str = "utility"


@dataclass
class GeneratedApp:
    name: str
    filepath: str
    code: str
    created_at: datetime = field(default_factory=datetime.now)
    validated: bool = False
    validation_errors: list = field(default_factory=list)
    audit_passed: bool = False


TEMPLATES = {
    "flask_api": CodeTemplate(
        name="Flask REST API",
        description="A minimal Flask REST API with CORS and error handling",
        category="web",
        template=textwrap.dedent('''\
            """
            {name} - Generated by J.A.R.V.I.S. V300
            {description}
            """
            from flask import Flask, jsonify, request
            from flask_cors import CORS

            app = Flask(__name__)
            CORS(app)


            @app.route("/api/health", methods=["GET"])
            def health():
                return jsonify({{"status": "ok", "service": "{name}"}})


            @app.route("/api/data", methods=["GET"])
            def get_data():
                return jsonify({{"data": [], "message": "Implement your logic here"}})


            @app.route("/api/data", methods=["POST"])
            def create_data():
                payload = request.get_json()
                if not payload:
                    return jsonify({{"error": "No data provided"}}), 400
                return jsonify({{"created": payload}}), 201


            @app.errorhandler(404)
            def not_found(e):
                return jsonify({{"error": "Not found"}}), 404


            @app.errorhandler(500)
            def server_error(e):
                return jsonify({{"error": "Internal server error"}}), 500


            if __name__ == "__main__":
                app.run(host="0.0.0.0", port=5000, debug=True)
        '''),
    ),
    "data_processor": CodeTemplate(
        name="Data Processor",
        description="CSV/JSON data processing pipeline",
        category="data",
        template=textwrap.dedent('''\
            """
            {name} - Generated by J.A.R.V.I.S. V300
            {description}
            """
            import csv
            import json
            import sys
            from pathlib import Path


            def load_csv(filepath: str) -> list[dict]:
                with open(filepath, "r", encoding="utf-8") as f:
                    return list(csv.DictReader(f))


            def load_json(filepath: str) -> list:
                with open(filepath, "r", encoding="utf-8") as f:
                    return json.load(f)


            def process(data: list[dict]) -> list[dict]:
                """Transform data - customize this function."""
                return [{{**row}} for row in data]


            def save_output(data: list[dict], filepath: str) -> None:
                with open(filepath, "w", encoding="utf-8") as f:
                    json.dump(data, f, indent=2, ensure_ascii=False)
                print(f"Saved {{len(data)}} records to {{filepath}}")


            def main():
                if len(sys.argv) < 2:
                    print("Usage: python {filename} <input_file> [output_file]")
                    sys.exit(1)

                input_file = sys.argv[1]
                output_file = sys.argv[2] if len(sys.argv) > 2 else "output.json"

                ext = Path(input_file).suffix.lower()
                if ext == ".csv":
                    data = load_csv(input_file)
                elif ext == ".json":
                    data = load_json(input_file)
                else:
                    print(f"Unsupported format: {{ext}}")
                    sys.exit(1)

                processed = process(data)
                save_output(processed, output_file)


            if __name__ == "__main__":
                main()
        '''),
    ),
    "scraper": CodeTemplate(
        name="Web Scraper",
        description="Configurable web scraper with rate limiting",
        category="web",
        template=textwrap.dedent('''\
            """
            {name} - Generated by J.A.R.V.I.S. V300
            {description}
            """
            import json
            import time
            from urllib.parse import urljoin

            import requests
            from bs4 import BeautifulSoup


            class Scraper:
                def __init__(self, base_url: str, delay: float = 1.0):
                    self.base_url = base_url
                    self.delay = delay
                    self.session = requests.Session()
                    self.session.headers.update({{
                        "User-Agent": "Mozilla/5.0 (compatible; JarvisBot/1.0)"
                    }})

                def fetch(self, path: str = "") -> str:
                    url = urljoin(self.base_url, path)
                    resp = self.session.get(url, timeout=10)
                    resp.raise_for_status()
                    time.sleep(self.delay)
                    return resp.text

                def parse(self, html: str, selector: str) -> list[str]:
                    soup = BeautifulSoup(html, "html.parser")
                    elements = soup.select(selector)
                    return [el.get_text(strip=True) for el in elements]

                def run(self, paths: list[str], selector: str) -> list[dict]:
                    results = []
                    for path in paths:
                        html = self.fetch(path)
                        items = self.parse(html, selector)
                        results.append({{"path": path, "items": items}})
                    return results


            if __name__ == "__main__":
                scraper = Scraper("https://example.com")
                data = scraper.run(["/"], "h1")
                print(json.dumps(data, indent=2))
        '''),
    ),
    "cli_tool": CodeTemplate(
        name="CLI Tool",
        description="Command-line tool with argparse",
        category="utility",
        template=textwrap.dedent('''\
            """
            {name} - Generated by J.A.R.V.I.S. V300
            {description}
            """
            import argparse
            import sys


            def setup_parser() -> argparse.ArgumentParser:
                parser = argparse.ArgumentParser(
                    description="{description}",
                    formatter_class=argparse.RawDescriptionHelpFormatter,
                )
                parser.add_argument("input", help="Input file or value")
                parser.add_argument("-o", "--output", default="-", help="Output file (default: stdout)")
                parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")
                return parser


            def run(args: argparse.Namespace) -> int:
                if args.verbose:
                    print(f"Processing: {{args.input}}")

                result = f"Processed: {{args.input}}"

                if args.output == "-":
                    print(result)
                else:
                    with open(args.output, "w") as f:
                        f.write(result + "\\n")
                    if args.verbose:
                        print(f"Written to: {{args.output}}")

                return 0


            def main():
                parser = setup_parser()
                args = parser.parse_args()
                sys.exit(run(args))


            if __name__ == "__main__":
                main()
        '''),
    ),
    "streamlit_app": CodeTemplate(
        name="Streamlit App",
        description="Interactive Streamlit dashboard",
        category="web",
        template=textwrap.dedent('''\
            """
            {name} - Generated by J.A.R.V.I.S. V300
            {description}
            """
            import streamlit as st
            import pandas as pd
            import plotly.express as px


            st.set_page_config(page_title="{name}", layout="wide")
            st.title("{name}")
            st.markdown("{description}")

            uploaded = st.file_uploader("Upload CSV", type=["csv"])
            if uploaded:
                df = pd.read_csv(uploaded)
                st.dataframe(df)

                numeric_cols = df.select_dtypes(include="number").columns.tolist()
                if numeric_cols:
                    col = st.selectbox("Select column to plot", numeric_cols)
                    fig = px.histogram(df, x=col, title=f"Distribution of {{col}}")
                    st.plotly_chart(fig, use_container_width=True)
            else:
                st.info("Upload a CSV file to get started.")
        '''),
    ),
}


class CodeValidator:
    """Validates Python code for syntax, imports, and basic quality."""

    def validate(self, code: str) -> tuple[bool, list[str]]:
        errors = []

        syntax_ok, syntax_errors = self._check_syntax(code)
        errors.extend(syntax_errors)

        import_errors = self._check_imports(code)
        errors.extend(import_errors)

        quality_issues = self._check_quality(code)
        errors.extend(quality_issues)

        return len(errors) == 0, errors

    @staticmethod
    def _check_syntax(code: str) -> tuple[bool, list[str]]:
        try:
            ast.parse(code)
            return True, []
        except SyntaxError as e:
            return False, [f"Syntax error at line {e.lineno}: {e.msg}"]

    @staticmethod
    def _check_imports(code: str) -> list[str]:
        warnings = []
        try:
            tree = ast.parse(code)
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        try:
                            importlib.import_module(alias.name)
                        except ImportError:
                            warnings.append(f"Import warning: '{alias.name}' not installed")
                elif isinstance(node, ast.ImportFrom):
                    if node.module:
                        try:
                            importlib.import_module(node.module)
                        except ImportError:
                            warnings.append(f"Import warning: '{node.module}' not installed")
        except SyntaxError:
            pass
        return warnings

    @staticmethod
    def _check_quality(code: str) -> list[str]:
        issues = []
        lines = code.splitlines()

        for i, line in enumerate(lines, 1):
            if len(line) > 120:
                issues.append(f"Line {i}: exceeds 120 characters ({len(line)})")

        try:
            tree = ast.parse(code)
            for node in ast.walk(tree):
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    body_lines = node.end_lineno - node.lineno if hasattr(node, "end_lineno") else 0
                    if body_lines > 50:
                        issues.append(f"Function '{node.name}' at line {node.lineno} is very long ({body_lines} lines)")
        except SyntaxError:
            pass

        return issues


class Coder:
    """Code generation and management engine."""

    def __init__(self, apps_dir: str):
        self.apps_dir = Path(apps_dir)
        self.apps_dir.mkdir(parents=True, exist_ok=True)
        self.validator = CodeValidator()
        self.generated_apps: list[GeneratedApp] = []

    def list_templates(self) -> list[dict]:
        return [
            {"key": k, "name": t.name, "description": t.description, "category": t.category}
            for k, t in TEMPLATES.items()
        ]

    def generate_from_template(
        self,
        template_key: str,
        app_name: str,
        description: str = "",
    ) -> Optional[GeneratedApp]:
        template = TEMPLATES.get(template_key)
        if not template:
            logger.error(f"Unknown template: {template_key}")
            return None

        filename = self._sanitize_filename(app_name) + ".py"
        filepath = str(self.apps_dir / filename)

        code = template.template.format(
            name=app_name,
            description=description or template.description,
            filename=filename,
        )

        return self._create_app(app_name, filepath, code)

    def generate_custom(self, app_name: str, code: str) -> Optional[GeneratedApp]:
        filename = self._sanitize_filename(app_name) + ".py"
        filepath = str(self.apps_dir / filename)
        return self._create_app(app_name, filepath, code)

    def _create_app(self, name: str, filepath: str, code: str) -> GeneratedApp:
        valid, errors = self.validator.validate(code)

        app = GeneratedApp(
            name=name,
            filepath=filepath,
            code=code,
            validated=valid,
            validation_errors=errors,
        )

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(code)

        self.generated_apps.append(app)
        logger.info(f"Generated app: {name} -> {filepath} (valid={valid})")

        if errors:
            for err in errors:
                logger.warning(f"  {err}")

        return app

    def run_app(self, app_name: str, args: list[str] = None) -> tuple[int, str, str]:
        filename = self._sanitize_filename(app_name) + ".py"
        filepath = self.apps_dir / filename

        if not filepath.exists():
            return -1, "", f"App not found: {filepath}"

        cmd = [sys.executable, str(filepath)] + (args or [])
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=30,
                cwd=str(self.apps_dir),
            )
            return result.returncode, result.stdout, result.stderr
        except subprocess.TimeoutExpired:
            return -1, "", "Execution timed out (30s)"
        except Exception as e:
            return -1, "", str(e)

    def list_apps(self) -> list[dict]:
        apps = []
        for py_file in sorted(self.apps_dir.glob("*.py")):
            apps.append({
                "name": py_file.stem,
                "filepath": str(py_file),
                "size": py_file.stat().st_size,
                "modified": datetime.fromtimestamp(py_file.stat().st_mtime).isoformat(),
            })
        return apps

    @staticmethod
    def _sanitize_filename(name: str) -> str:
        sanitized = "".join(c if c.isalnum() or c == "_" else "_" for c in name.lower())
        return sanitized.strip("_") or "app"

    def get_status(self) -> dict:
        return {
            "apps_dir": str(self.apps_dir),
            "total_apps": len(self.list_apps()),
            "generated_this_session": len(self.generated_apps),
            "templates_available": len(TEMPLATES),
        }
