//+------------------------------------------------------------------+
//|                                          {{ ea_name }}.mq5       |
//|                        Generated by JARVIS AI Trading OS          |
//|                                                                  |
//+------------------------------------------------------------------+
#property copyright "JARVIS AI Trading OS"
#property link      ""
#property version   "1.00"
#property strict

//--- Input parameters
input int      MagicNumber       = {{ magic_number }};
input double   DefaultLotSize    = {{ default_lot }};
input double   DefaultSL         = {{ default_sl }};         // Stop Loss in points
input double   DefaultTP         = {{ default_tp }};         // Take Profit in points
input double   RiskPercent       = {{ risk_percent }};       // Risk per trade (%)
input bool     UseFixedLot       = {{ use_fixed_lot }};
input int      MaxSlippage       = {{ max_slippage }};       // Maximum slippage in points
input int      MaxConcurrentTrades = 1;                      // Max concurrent trades
input double   EmergencyStopPct  = 20.0;                     // Emergency stop loss (% of balance)

//--- Trailing stop inputs
input bool     UseTrailingStop    = {{ use_trailing_stop }};
input double   TrailingActivation = {{ trailing_activation }}; // Pips profit to activate
input double   TrailingDistance   = {{ trailing_distance }};   // Trail distance in pips
input double   TrailingStep      = {{ trailing_step }};        // Minimum step in pips

{% if extra_inputs %}
//--- Strategy-specific inputs
{{ extra_inputs }}
{% endif %}

//--- Global variables
int            g_ticket = -1;
datetime       g_lastTradeTime = 0;
double         g_peakEquity = 0;
bool           g_dailyLimitHit = false;
datetime       g_lastDay = 0;
double         g_dailyStartBalance = 0;

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>
#include <Trade\SymbolInfo.mqh>

CTrade         g_trade;
CPositionInfo  g_posInfo;
CSymbolInfo    g_symInfo;

{% if custom_includes %}
{{ custom_includes }}
{% endif %}

//+------------------------------------------------------------------+
//| Expert initialization function                                     |
//+------------------------------------------------------------------+
int OnInit()
{
   g_trade.SetExpertMagicNumber(MagicNumber);
   g_trade.SetDeviationInPoints(MaxSlippage);
   g_trade.SetTypeFilling(ORDER_FILLING_IOC);

   g_symInfo.Name(_Symbol);
   g_symInfo.Refresh();

   g_peakEquity = AccountInfoDouble(ACCOUNT_EQUITY);
   g_dailyStartBalance = AccountInfoDouble(ACCOUNT_BALANCE);
   g_lastDay = iTime(_Symbol, PERIOD_D1, 0);

   Print("{{ ea_name }} initialized on ", _Symbol,
         " | Magic=", MagicNumber,
         " | Lot=", DefaultLotSize,
         " | SL=", DefaultSL,
         " | TP=", DefaultTP);

{% if on_init_extra %}
   {{ on_init_extra }}
{% endif %}

   return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                   |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
{% if on_deinit_extra %}
   {{ on_deinit_extra }}
{% endif %}
   Print("{{ ea_name }} deinitialized. Reason: ", reason);
}

//+------------------------------------------------------------------+
//| Expert tick function                                               |
//+------------------------------------------------------------------+
void OnTick()
{
   //--- Refresh symbol data
   g_symInfo.Refresh();

   //--- Reset daily limits on new day
   datetime currentDay = iTime(_Symbol, PERIOD_D1, 0);
   if(currentDay != g_lastDay)
   {
      g_lastDay = currentDay;
      g_dailyLimitHit = false;
      g_dailyStartBalance = AccountInfoDouble(ACCOUNT_BALANCE);
   }

   //--- Check emergency stop on open positions
   CheckEmergencyStop();

   //--- Apply trailing stop
   if(UseTrailingStop)
      ApplyTrailingStop();

   //--- Update peak equity for drawdown tracking
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   if(equity > g_peakEquity)
      g_peakEquity = equity;

   //--- Skip if daily loss limit hit
   if(g_dailyLimitHit)
      return;

{% if strategy_logic %}
   //--- Strategy logic
   {{ strategy_logic }}
{% endif %}

   //--- Count open positions for this EA
   int openCount = CountOpenPositions();

   //--- Enforce max concurrent trades
   if(openCount >= MaxConcurrentTrades)
      return;

   //--- Check entry conditions
   bool buySignal  = CheckBuyCondition();
   bool sellSignal = CheckSellCondition();

   //--- Never open buy and sell simultaneously
   if(buySignal && sellSignal)
   {
      buySignal = false;
      sellSignal = false;
   }

   //--- Prevent opening opposite direction to existing trade
   if(openCount > 0)
   {
      if(buySignal && HasSellPosition())
         buySignal = false;
      if(sellSignal && HasBuyPosition())
         sellSignal = false;
   }

   //--- Execute trades
   if(buySignal)
      OpenBuy();
   if(sellSignal)
      OpenSell();
}

//+------------------------------------------------------------------+
//| Check buy entry condition                                         |
//+------------------------------------------------------------------+
bool CheckBuyCondition()
{
{% if entry_condition_buy %}
   {{ entry_condition_buy }}
{% else %}
   return false;
{% endif %}
}

//+------------------------------------------------------------------+
//| Check sell entry condition                                        |
//+------------------------------------------------------------------+
bool CheckSellCondition()
{
{% if entry_condition_sell %}
   {{ entry_condition_sell }}
{% else %}
   return false;
{% endif %}
}

{% if exit_condition_buy %}
//+------------------------------------------------------------------+
//| Check buy exit condition                                          |
//+------------------------------------------------------------------+
bool CheckBuyExitCondition()
{
   {{ exit_condition_buy }}
}
{% endif %}

{% if exit_condition_sell %}
//+------------------------------------------------------------------+
//| Check sell exit condition                                         |
//+------------------------------------------------------------------+
bool CheckSellExitCondition()
{
   {{ exit_condition_sell }}
}
{% endif %}

//+------------------------------------------------------------------+
//| Open a BUY position                                               |
//+------------------------------------------------------------------+
void OpenBuy()
{
   double ask = g_symInfo.Ask();
   double sl  = (DefaultSL > 0) ? NormalizeDouble(ask - DefaultSL * _Point, _Digits) : 0;
   double tp  = (DefaultTP > 0) ? NormalizeDouble(ask + DefaultTP * _Point, _Digits) : 0;
   double lot = CalculateLotSize();

   if(g_trade.Buy(lot, _Symbol, ask, sl, tp, "{{ ea_name }}"))
   {
      g_ticket = (int)g_trade.ResultOrder();
      g_lastTradeTime = TimeCurrent();
      Print("BUY opened: ticket=", g_ticket, " price=", ask, " lot=", lot, " sl=", sl, " tp=", tp);
   }
   else
   {
      Print("BUY failed: ", g_trade.ResultRetcodeDescription());
   }
}

//+------------------------------------------------------------------+
//| Open a SELL position                                              |
//+------------------------------------------------------------------+
void OpenSell()
{
   double bid = g_symInfo.Bid();
   double sl  = (DefaultSL > 0) ? NormalizeDouble(bid + DefaultSL * _Point, _Digits) : 0;
   double tp  = (DefaultTP > 0) ? NormalizeDouble(bid - DefaultTP * _Point, _Digits) : 0;
   double lot = CalculateLotSize();

   if(g_trade.Sell(lot, _Symbol, bid, sl, tp, "{{ ea_name }}"))
   {
      g_ticket = (int)g_trade.ResultOrder();
      g_lastTradeTime = TimeCurrent();
      Print("SELL opened: ticket=", g_ticket, " price=", bid, " lot=", lot, " sl=", sl, " tp=", tp);
   }
   else
   {
      Print("SELL failed: ", g_trade.ResultRetcodeDescription());
   }
}

//+------------------------------------------------------------------+
//| Calculate lot size based on risk                                  |
//+------------------------------------------------------------------+
double CalculateLotSize()
{
   if(UseFixedLot)
      return DefaultLotSize;

   double balance   = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskMoney = balance * RiskPercent / 100.0;

   if(DefaultSL <= 0)
      return DefaultLotSize;

   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);

   if(tickValue <= 0 || tickSize <= 0)
      return DefaultLotSize;

   double slMoney  = DefaultSL * _Point * tickValue / tickSize;
   double lot      = (slMoney > 0) ? riskMoney / slMoney : DefaultLotSize;

   double minLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double stepLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);

   lot = MathMax(minLot, MathMin(lot, maxLot));
   if(stepLot > 0)
      lot = MathFloor(lot / stepLot) * stepLot;

   return NormalizeDouble(lot, 2);
}

//+------------------------------------------------------------------+
//| Count open positions for this EA                                  |
//+------------------------------------------------------------------+
int CountOpenPositions()
{
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(g_posInfo.SelectByIndex(i))
      {
         if(g_posInfo.Magic() == MagicNumber && g_posInfo.Symbol() == _Symbol)
            count++;
      }
   }
   return count;
}

//+------------------------------------------------------------------+
//| Check if a BUY position exists                                    |
//+------------------------------------------------------------------+
bool HasBuyPosition()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(g_posInfo.SelectByIndex(i))
      {
         if(g_posInfo.Magic() == MagicNumber && g_posInfo.Symbol() == _Symbol
            && g_posInfo.PositionType() == POSITION_TYPE_BUY)
            return true;
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Check if a SELL position exists                                   |
//+------------------------------------------------------------------+
bool HasSellPosition()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(g_posInfo.SelectByIndex(i))
      {
         if(g_posInfo.Magic() == MagicNumber && g_posInfo.Symbol() == _Symbol
            && g_posInfo.PositionType() == POSITION_TYPE_SELL)
            return true;
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Emergency stop: close if loss >= threshold % of balance           |
//+------------------------------------------------------------------+
void CheckEmergencyStop()
{
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   if(balance <= 0)
      return;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(!g_posInfo.SelectByIndex(i))
         continue;
      if(g_posInfo.Magic() != MagicNumber || g_posInfo.Symbol() != _Symbol)
         continue;

      double profit = g_posInfo.Profit() + g_posInfo.Swap() + g_posInfo.Commission();
      double lossPct = MathAbs(profit) / balance * 100.0;

      if(profit < 0 && lossPct >= EmergencyStopPct)
      {
         Print("EMERGENCY STOP: ticket=", g_posInfo.Ticket(),
               " loss=", profit, " (", NormalizeDouble(lossPct, 1), "% of balance)");
         g_trade.PositionClose(g_posInfo.Ticket());
      }
   }

   //--- Daily loss limit (5 % of starting balance)
   double dayPnL = AccountInfoDouble(ACCOUNT_BALANCE) - g_dailyStartBalance;
   double unrealized = AccountInfoDouble(ACCOUNT_EQUITY) - AccountInfoDouble(ACCOUNT_BALANCE);
   double totalDayPnL = dayPnL + unrealized;
   if(totalDayPnL < 0 && MathAbs(totalDayPnL) / g_dailyStartBalance * 100.0 >= 5.0)
   {
      if(!g_dailyLimitHit)
      {
         Print("DAILY LOSS LIMIT HIT. Closing all positions.");
         g_dailyLimitHit = true;
         CloseAllPositions();
      }
   }
}

//+------------------------------------------------------------------+
//| Close all positions for this EA                                   |
//+------------------------------------------------------------------+
void CloseAllPositions()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(g_posInfo.SelectByIndex(i))
      {
         if(g_posInfo.Magic() == MagicNumber && g_posInfo.Symbol() == _Symbol)
            g_trade.PositionClose(g_posInfo.Ticket());
      }
   }
}

//+------------------------------------------------------------------+
//| Trailing stop logic                                               |
//+------------------------------------------------------------------+
void ApplyTrailingStop()
{
   double point = _Point;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(!g_posInfo.SelectByIndex(i))
         continue;
      if(g_posInfo.Magic() != MagicNumber || g_posInfo.Symbol() != _Symbol)
         continue;

      double openPrice   = g_posInfo.PriceOpen();
      double currentSL   = g_posInfo.StopLoss();
      double currentTP   = g_posInfo.TakeProfit();
      ulong  ticket      = g_posInfo.Ticket();

      if(g_posInfo.PositionType() == POSITION_TYPE_BUY)
      {
         double bid = g_symInfo.Bid();
         double profitPips = (bid - openPrice) / point;

         if(profitPips >= TrailingActivation)
         {
            double newSL = NormalizeDouble(bid - TrailingDistance * point, _Digits);

            if(newSL > currentSL + TrailingStep * point || currentSL == 0)
            {
               if(g_trade.PositionModify(ticket, newSL, currentTP))
                  Print("Trailing BUY: ticket=", ticket, " newSL=", newSL);
            }
         }
      }
      else if(g_posInfo.PositionType() == POSITION_TYPE_SELL)
      {
         double ask = g_symInfo.Ask();
         double profitPips = (openPrice - ask) / point;

         if(profitPips >= TrailingActivation)
         {
            double newSL = NormalizeDouble(ask + TrailingDistance * point, _Digits);

            if((newSL < currentSL - TrailingStep * point) || currentSL == 0)
            {
               if(g_trade.PositionModify(ticket, newSL, currentTP))
                  Print("Trailing SELL: ticket=", ticket, " newSL=", newSL);
            }
         }
      }
   }
}

{% if custom_functions %}
//+------------------------------------------------------------------+
//| Custom strategy functions                                         |
//+------------------------------------------------------------------+
{{ custom_functions }}
{% endif %}
//+------------------------------------------------------------------+
