"""
JARVIS MQL5 Generator - Generates complete, functional MQL5 Expert Advisors and Indicators
"""
from pathlib import Path
from typing import Dict, List, Optional
from dataclasses import dataclass, field
import json
import shutil
from loguru import logger


class MQL5Generator:
    """Generates production-ready MQL5 Expert Advisors and Indicators"""

    OUTPUT_DIR = Path("/workspace/mql5/generated")

    def __init__(self):
        self.OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        (self.OUTPUT_DIR / "experts").mkdir(exist_ok=True)
        (self.OUTPUT_DIR / "indicators").mkdir(exist_ok=True)
        (self.OUTPUT_DIR / "include").mkdir(exist_ok=True)

    # ------------------------------------------------------------------
    # Main EA generator (config-driven)
    # ------------------------------------------------------------------

    def generate_expert_advisor(self, config: Dict) -> str:
        """Generate complete EA .mq5 file content from a config dict.

        Config keys:
            name            – EA display name
            strategy_type   – "scalping" | "trend" | "mean_reversion" | "breakout" | "ict"
            symbols         – list of symbols (first is primary)
            timeframes      – list like ["M5", "M15"]
            risk_percent    – float, default 2.0
            max_sl_pips     – int, default 30
            tp_multiplier   – float, default 2.0 (TP = SL * multiplier)
            use_trailing    – bool
            trailing_start  – pips before trailing activates
            trailing_step   – trailing step in pips
            magic_number    – int
            indicators      – list of indicator configs
            conditions      – dict with buy/sell condition strings
        """
        name = config.get("name", "JARVIS_EA")
        strategy_type = config.get("strategy_type", "trend")
        symbol = (config.get("symbols") or ["XAUUSD"])[0]
        timeframe = (config.get("timeframes") or ["H1"])[0]
        risk_percent = config.get("risk_percent", 2.0)
        max_sl_pips = config.get("max_sl_pips", 30)
        tp_multiplier = config.get("tp_multiplier", 2.0)
        use_trailing = config.get("use_trailing", True)
        trailing_start = config.get("trailing_start", 20)
        trailing_step = config.get("trailing_step", 5)
        magic_number = config.get("magic_number", 99999)
        conditions = config.get("conditions", {})

        buy_cond = conditions.get("buy", "rsiValue < 30 && stochMain < 20")
        sell_cond = conditions.get("sell", "rsiValue > 70 && stochMain > 80")

        tp_pips = int(max_sl_pips * tp_multiplier)
        trailing_str = "true" if use_trailing else "false"
        tf_const = f"PERIOD_{timeframe}"

        code = f'''//+------------------------------------------------------------------+
//| {name}.mq5                                                        |
//| JARVIS AI Trading System                                          |
//| Generated by JARVIS MQL5 Generator                               |
//+------------------------------------------------------------------+
#property copyright "JARVIS AI"
#property version   "1.00"
#property strict

#include <Trade\\Trade.mqh>
#include <Trade\\PositionInfo.mqh>
#include <Trade\\AccountInfo.mqh>

// === Trading Settings ===
input group "=== Trading Settings ==="
input double   InpRiskPercent      = {risk_percent};
input int      InpMagicNumber      = {magic_number};
input string   InpComment          = "JARVIS_{strategy_type.upper()}";

input group "=== Stop Loss / Take Profit ==="
input int      InpStopLoss         = {max_sl_pips};
input int      InpTakeProfit       = {tp_pips};
input bool     InpUseTrailingStop  = {trailing_str};
input int      InpTrailingStart    = {trailing_start};
input int      InpTrailingStep     = {trailing_step};

input group "=== Indicator Settings ==="
input int      InpRSIPeriod        = 14;
input int      InpStochK           = 5;
input int      InpStochD           = 3;
input int      InpEMAFast          = 20;
input int      InpEMASlow          = 50;

// Global variables
CTrade         Trade;
CPositionInfo  PositionInfo;
CAccountInfo   AccountInfo;

int  handleRSI;
int  handleStoch;
int  handleEMAFast;
int  handleEMASlow;
bool isNewBar      = false;
datetime lastBar   = 0;

//+------------------------------------------------------------------+
int OnInit()
{{
   Trade.SetExpertMagicNumber(InpMagicNumber);
   Trade.SetDeviationInPoints(10);
   Trade.SetTypeFilling(ORDER_FILLING_FOK);

   handleRSI     = iRSI(_Symbol, {tf_const}, InpRSIPeriod, PRICE_CLOSE);
   handleStoch   = iStochastic(_Symbol, {tf_const}, InpStochK, InpStochD, 3, MODE_SMA, STO_LOWHIGH);
   handleEMAFast = iMA(_Symbol, {tf_const}, InpEMAFast, 0, MODE_EMA, PRICE_CLOSE);
   handleEMASlow = iMA(_Symbol, {tf_const}, InpEMASlow, 0, MODE_EMA, PRICE_CLOSE);

   if(handleRSI == INVALID_HANDLE || handleStoch == INVALID_HANDLE ||
      handleEMAFast == INVALID_HANDLE || handleEMASlow == INVALID_HANDLE)
   {{
      Print("Error creating indicator handles: ", GetLastError());
      return INIT_FAILED;
   }}

   Print("{name} initialised on ", _Symbol, " / {timeframe}");
   return INIT_SUCCEEDED;
}}

//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{{
   IndicatorRelease(handleRSI);
   IndicatorRelease(handleStoch);
   IndicatorRelease(handleEMAFast);
   IndicatorRelease(handleEMASlow);
}}

//+------------------------------------------------------------------+
void OnTick()
{{
   if(!IsNewBar()) return;
   if(!TerminalInfoInteger(TERMINAL_TRADE_ALLOWED)) return;

   double rsiBuffer[3], stochMain[3], stochSignal[3], emaFast[3], emaSlow[3];

   if(CopyBuffer(handleRSI,     0, 1, 3, rsiBuffer)  < 3) return;
   if(CopyBuffer(handleStoch,   0, 1, 3, stochMain)  < 3) return;
   if(CopyBuffer(handleStoch,   1, 1, 3, stochSignal)< 3) return;
   if(CopyBuffer(handleEMAFast, 0, 1, 3, emaFast)    < 3) return;
   if(CopyBuffer(handleEMASlow, 0, 1, 3, emaSlow)    < 3) return;

   double rsiValue    = rsiBuffer[0];
   double stochValue  = stochMain[0];
   double emaFastVal  = emaFast[0];
   double emaSlowVal  = emaSlow[0];

   ManageOpenPositions();

   int posCount = CountPositions();
   if(posCount > 0) return;

   // Buy condition: {buy_cond}
   bool buySignal  = ({buy_cond});
   // Sell condition: {sell_cond}
   bool sellSignal = ({sell_cond});

   if(buySignal)  OpenBuy();
   if(sellSignal) OpenSell();
}}

//+------------------------------------------------------------------+
void OpenBuy()
{{
   double ask     = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double sl      = ask - InpStopLoss * _Point * 10;
   double tp      = ask + InpTakeProfit * _Point * 10;
   double lots    = CalculateLotSize(InpStopLoss * _Point * 10);

   if(lots <= 0) return;

   if(!Trade.Buy(lots, _Symbol, ask, sl, tp, InpComment))
      Print("Buy failed: ", Trade.ResultRetcodeDescription());
}}

//+------------------------------------------------------------------+
void OpenSell()
{{
   double bid  = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl   = bid + InpStopLoss * _Point * 10;
   double tp   = bid - InpTakeProfit * _Point * 10;
   double lots = CalculateLotSize(InpStopLoss * _Point * 10);

   if(lots <= 0) return;

   if(!Trade.Sell(lots, _Symbol, bid, sl, tp, InpComment))
      Print("Sell failed: ", Trade.ResultRetcodeDescription());
}}

//+------------------------------------------------------------------+
void ManageOpenPositions()
{{
   if(!InpUseTrailingStop) return;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      if(!PositionInfo.SelectByIndex(i)) continue;
      if(PositionInfo.Symbol() != _Symbol) continue;
      if(PositionInfo.Magic()  != InpMagicNumber) continue;

      ApplyTrailingStop(PositionInfo.Ticket(), PositionInfo.PositionType(),
                        PositionInfo.PriceOpen(), PositionInfo.StopLoss());
   }}
}}

//+------------------------------------------------------------------+
void ApplyTrailingStop(ulong ticket, ENUM_POSITION_TYPE type,
                       double openPrice, double currentSL)
{{
   double ask  = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid  = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double step = InpTrailingStep  * _Point * 10;
   double start= InpTrailingStart * _Point * 10;

   double newSL = 0;

   if(type == POSITION_TYPE_BUY)
   {{
      if(bid - openPrice < start) return;
      newSL = bid - InpTrailingStep * _Point * 10;
      if(newSL <= currentSL + step) return;
   }}
   else
   {{
      if(openPrice - ask < start) return;
      newSL = ask + InpTrailingStep * _Point * 10;
      if(newSL >= currentSL - step || currentSL == 0) return;
   }}

   Trade.PositionModify(ticket, newSL, PositionInfo.TakeProfit());
}}

//+------------------------------------------------------------------+
double CalculateLotSize(double slDistance)
{{
   double balance    = AccountInfo.Balance();
   double riskAmount = balance * InpRiskPercent / 100.0;
   double tickValue  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize   = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);

   if(tickSize == 0 || tickValue == 0 || slDistance == 0) return 0;

   double lots = riskAmount / (slDistance / tickSize * tickValue);
   double minLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);

   lots = MathFloor(lots / lotStep) * lotStep;
   lots = MathMax(minLot, MathMin(maxLot, lots));
   return lots;
}}

//+------------------------------------------------------------------+
int CountPositions()
{{
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      if(PositionInfo.SelectByIndex(i) &&
         PositionInfo.Symbol() == _Symbol &&
         PositionInfo.Magic()  == InpMagicNumber)
         count++;
   }}
   return count;
}}

//+------------------------------------------------------------------+
bool IsNewBar()
{{
   datetime currentBar = iTime(_Symbol, {tf_const}, 0);
   if(currentBar == lastBar) return false;
   lastBar = currentBar;
   return true;
}}
'''
        return code

    # ------------------------------------------------------------------
    # Specialised EA generators
    # ------------------------------------------------------------------

    def generate_scalping_ea(self, name: str, symbol: str = "XAUUSD") -> str:
        """Generate Gold scalping EA with RSI + Stochastic signals"""
        return f'''//+------------------------------------------------------------------+
//| {name}.mq5                                                        |
//| JARVIS AI Trading System - Gold Scalper                          |
//+------------------------------------------------------------------+
#property copyright "JARVIS AI"
#property version   "1.00"
#property strict

#include <Trade\\Trade.mqh>
#include <Trade\\PositionInfo.mqh>
#include <Trade\\AccountInfo.mqh>

input group "=== Trading Settings ==="
input double   InpRiskPercent      = 1.0;
input int      InpMagicNumber      = 11001;
input string   InpComment          = "JARVIS_SCALPER";
input int      InpMaxTrades        = 3;

input group "=== Stop Loss / Take Profit ==="
input int      InpStopLoss         = 25;
input int      InpTakeProfit       = 50;
input bool     InpUseTrailingStop  = true;
input int      InpTrailingStart    = 15;
input int      InpTrailingStep     = 5;

input group "=== RSI Settings ==="
input int      InpRSIPeriod        = 14;
input double   InpRSIOversold      = 30.0;
input double   InpRSIOverbought    = 70.0;

input group "=== Stochastic Settings ==="
input int      InpStochK           = 5;
input int      InpStochD           = 3;
input int      InpStochSlowing     = 3;
input double   InpStochOversold    = 20.0;
input double   InpStochOverbought  = 80.0;

input group "=== ATR Filter ==="
input int      InpATRPeriod        = 14;
input double   InpMinATR           = 0.5;
input double   InpMaxATR           = 5.0;

input group "=== Session Filter ==="
input bool     InpLondonSession    = true;
input bool     InpNewYorkSession   = true;

CTrade        Trade;
CPositionInfo PositionInfo;
CAccountInfo  AccountInfo;

int     handleRSI, handleStoch, handleATR;
datetime lastBar = 0;

//+------------------------------------------------------------------+
int OnInit()
{{
   Trade.SetExpertMagicNumber(InpMagicNumber);
   Trade.SetDeviationInPoints(20);
   Trade.SetTypeFilling(ORDER_FILLING_FOK);

   handleRSI   = iRSI(_Symbol, PERIOD_M5, InpRSIPeriod, PRICE_CLOSE);
   handleStoch = iStochastic(_Symbol, PERIOD_M5, InpStochK, InpStochD,
                              InpStochSlowing, MODE_SMA, STO_LOWHIGH);
   handleATR   = iATR(_Symbol, PERIOD_M5, InpATRPeriod);

   if(handleRSI   == INVALID_HANDLE ||
      handleStoch == INVALID_HANDLE ||
      handleATR   == INVALID_HANDLE)
   {{
      Print("Failed to create indicator handles. Error: ", GetLastError());
      return INIT_FAILED;
   }}

   Print("{name} initialised on ", _Symbol, " M5");
   return INIT_SUCCEEDED;
}}

//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{{
   IndicatorRelease(handleRSI);
   IndicatorRelease(handleStoch);
   IndicatorRelease(handleATR);
}}

//+------------------------------------------------------------------+
void OnTick()
{{
   datetime currentBar = iTime(_Symbol, PERIOD_M5, 0);
   if(currentBar == lastBar) return;
   lastBar = currentBar;

   if(!TerminalInfoInteger(TERMINAL_TRADE_ALLOWED)) return;
   if(!IsSessionActive()) return;

   double rsi[2], stochMain[2], stochSig[2], atr[2];
   if(CopyBuffer(handleRSI,   0, 1, 2, rsi)       < 2) return;
   if(CopyBuffer(handleStoch, 0, 1, 2, stochMain) < 2) return;
   if(CopyBuffer(handleStoch, 1, 1, 2, stochSig)  < 2) return;
   if(CopyBuffer(handleATR,   0, 1, 2, atr)       < 2) return;

   ManagePositions();

   if(CountPositions() >= InpMaxTrades) return;
   if(!IsATRValid(atr[0])) return;

   bool buySignal  = rsi[0] < InpRSIOversold   && stochMain[0] < InpStochOversold  &&
                     stochMain[0] > stochSig[0] && stochMain[1] <= stochSig[1];
   bool sellSignal = rsi[0] > InpRSIOverbought  && stochMain[0] > InpStochOverbought &&
                     stochMain[0] < stochSig[0] && stochMain[1] >= stochSig[1];

   if(buySignal)  OpenBuy();
   if(sellSignal) OpenSell();
}}

//+------------------------------------------------------------------+
void OpenBuy()
{{
   double ask  = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double sl   = ask - InpStopLoss   * _Point * 10;
   double tp   = ask + InpTakeProfit * _Point * 10;
   double lots = CalculateLots(InpStopLoss * _Point * 10);
   if(lots <= 0) return;
   if(!Trade.Buy(lots, _Symbol, ask, sl, tp, InpComment))
      Print("Buy error: ", Trade.ResultRetcodeDescription());
}}

//+------------------------------------------------------------------+
void OpenSell()
{{
   double bid  = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl   = bid + InpStopLoss   * _Point * 10;
   double tp   = bid - InpTakeProfit * _Point * 10;
   double lots = CalculateLots(InpStopLoss * _Point * 10);
   if(lots <= 0) return;
   if(!Trade.Sell(lots, _Symbol, bid, sl, tp, InpComment))
      Print("Sell error: ", Trade.ResultRetcodeDescription());
}}

//+------------------------------------------------------------------+
void ManagePositions()
{{
   if(!InpUseTrailingStop) return;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      if(!PositionInfo.SelectByIndex(i)) continue;
      if(PositionInfo.Symbol() != _Symbol || PositionInfo.Magic() != InpMagicNumber) continue;

      ulong ticket  = PositionInfo.Ticket();
      double open   = PositionInfo.PriceOpen();
      double curSL  = PositionInfo.StopLoss();
      double curTP  = PositionInfo.TakeProfit();
      double ask    = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double bid    = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      double step   = InpTrailingStep  * _Point * 10;
      double start  = InpTrailingStart * _Point * 10;

      if(PositionInfo.PositionType() == POSITION_TYPE_BUY)
      {{
         if(bid - open < start) continue;
         double newSL = bid - step;
         if(newSL > curSL + step)
            Trade.PositionModify(ticket, newSL, curTP);
      }}
      else
      {{
         if(open - ask < start) continue;
         double newSL = ask + step;
         if(curSL == 0 || newSL < curSL - step)
            Trade.PositionModify(ticket, newSL, curTP);
      }}
   }}
}}

//+------------------------------------------------------------------+
bool IsSessionActive()
{{
   MqlDateTime t;
   TimeToStruct(TimeGMT(), t);
   int hour = t.hour;
   bool london   = InpLondonSession  && hour >= 7  && hour < 16;
   bool newyork  = InpNewYorkSession && hour >= 13 && hour < 21;
   return london || newyork;
}}

//+------------------------------------------------------------------+
bool IsATRValid(double atrVal)
{{
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   double atrPips = atrVal / (point * 10);
   return atrPips >= InpMinATR && atrPips <= InpMaxATR;
}}

//+------------------------------------------------------------------+
double CalculateLots(double slDist)
{{
   double balance   = AccountInfo.Balance();
   double risk      = balance * InpRiskPercent / 100.0;
   double tickVal   = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickSize == 0 || tickVal == 0 || slDist == 0) return 0;
   double lots     = risk / (slDist / tickSize * tickVal);
   double minLot   = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot   = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lots = MathFloor(lots / lotStep) * lotStep;
   return MathMax(minLot, MathMin(maxLot, lots));
}}

//+------------------------------------------------------------------+
int CountPositions()
{{
   int cnt = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
      if(PositionInfo.SelectByIndex(i) &&
         PositionInfo.Symbol() == _Symbol &&
         PositionInfo.Magic()  == InpMagicNumber) cnt++;
   return cnt;
}}
'''

    def generate_ict_ea(self, name: str) -> str:
        """Generate ICT strategy EA with order blocks and FVG detection"""
        return f'''//+------------------------------------------------------------------+
//| {name}.mq5                                                        |
//| JARVIS AI Trading System - ICT Strategy                          |
//+------------------------------------------------------------------+
#property copyright "JARVIS AI"
#property version   "1.00"
#property strict

#include <Trade\\Trade.mqh>
#include <Trade\\PositionInfo.mqh>
#include <Trade\\AccountInfo.mqh>

input group "=== Trading Settings ==="
input double InpRiskPercent   = 1.0;
input int    InpMagicNumber   = 22001;
input string InpComment       = "JARVIS_ICT";

input group "=== ICT Settings ==="
input int    InpOBLookback    = 20;     // Order block lookback bars
input double InpFVGMinSize    = 5.0;    // Min FVG size in pips
input bool   InpUseKillzones  = true;   // Trade only in kill zones
input bool   InpUseMSS        = true;   // Market structure shift filter

input group "=== Risk Settings ==="
input int    InpStopLoss      = 30;
input int    InpTakeProfit    = 90;
input bool   InpUseTrailing   = true;
input int    InpTrailingStart = 30;
input int    InpTrailingStep  = 10;

CTrade        Trade;
CPositionInfo PositionInfo;
CAccountInfo  AccountInfo;

struct OrderBlock
{{
   double high;
   double low;
   bool   isBullish;
   datetime time;
   bool   mitigated;
}};

struct FVG
{{
   double upper;
   double lower;
   bool   isBullish;
   datetime time;
   bool   filled;
}};

OrderBlock bullishOBs[];
OrderBlock bearishOBs[];
FVG        fvgs[];
datetime   lastBar = 0;

//+------------------------------------------------------------------+
int OnInit()
{{
   Trade.SetExpertMagicNumber(InpMagicNumber);
   Trade.SetDeviationInPoints(20);
   Trade.SetTypeFilling(ORDER_FILLING_FOK);
   Print("{name} (ICT) initialised on ", _Symbol);
   return INIT_SUCCEEDED;
}}

//+------------------------------------------------------------------+
void OnDeinit(const int reason) {{ }}

//+------------------------------------------------------------------+
void OnTick()
{{
   datetime currentBar = iTime(_Symbol, PERIOD_H1, 0);
   if(currentBar == lastBar) return;
   lastBar = currentBar;

   if(!TerminalInfoInteger(TERMINAL_TRADE_ALLOWED)) return;
   if(InpUseKillzones && !IsKillzone()) return;

   ScanOrderBlocks();
   ScanFVGs();
   ManagePositions();
   if(CountPositions() > 0) return;

   CheckEntrySignals();
}}

//+------------------------------------------------------------------+
void ScanOrderBlocks()
{{
   ArrayFree(bullishOBs);
   ArrayFree(bearishOBs);

   int bars = MathMin(InpOBLookback, iBars(_Symbol, PERIOD_H1));
   for(int i = bars; i >= 2; i--)
   {{
      double o1 = iOpen (_Symbol, PERIOD_H1, i);
      double c1 = iClose(_Symbol, PERIOD_H1, i);
      double h1 = iHigh (_Symbol, PERIOD_H1, i);
      double l1 = iLow  (_Symbol, PERIOD_H1, i);
      double o0 = iOpen (_Symbol, PERIOD_H1, i-1);
      double c0 = iClose(_Symbol, PERIOD_H1, i-1);

      // Bullish OB: down-candle before significant up-move
      if(c1 < o1 && c0 > o0 && (c0 - o0) > (o1 - c1) * 1.5)
      {{
         OrderBlock ob;
         ob.high      = h1;
         ob.low       = l1;
         ob.isBullish = true;
         ob.time      = iTime(_Symbol, PERIOD_H1, i);
         ob.mitigated = false;
         int sz = ArraySize(bullishOBs);
         ArrayResize(bullishOBs, sz + 1);
         bullishOBs[sz] = ob;
      }}

      // Bearish OB: up-candle before significant down-move
      if(c1 > o1 && c0 < o0 && (o0 - c0) > (c1 - o1) * 1.5)
      {{
         OrderBlock ob;
         ob.high      = h1;
         ob.low       = l1;
         ob.isBullish = false;
         ob.time      = iTime(_Symbol, PERIOD_H1, i);
         ob.mitigated = false;
         int sz = ArraySize(bearishOBs);
         ArrayResize(bearishOBs, sz + 1);
         bearishOBs[sz] = ob;
      }}
   }}
}}

//+------------------------------------------------------------------+
void ScanFVGs()
{{
   ArrayFree(fvgs);
   int bars = MathMin(InpOBLookback, iBars(_Symbol, PERIOD_H1));
   double minSize = InpFVGMinSize * _Point * 10;

   for(int i = bars; i >= 1; i--)
   {{
      double h_prev = iHigh(_Symbol, PERIOD_H1, i+1);
      double l_prev = iLow (_Symbol, PERIOD_H1, i+1);
      double h_curr = iHigh(_Symbol, PERIOD_H1, i);
      double l_curr = iLow (_Symbol, PERIOD_H1, i);
      double h_next = iHigh(_Symbol, PERIOD_H1, i-1);
      double l_next = iLow (_Symbol, PERIOD_H1, i-1);

      // Bullish FVG: gap between candle[i+1] high and candle[i-1] low
      if(l_next > h_prev && (l_next - h_prev) >= minSize)
      {{
         FVG fvg;
         fvg.upper     = l_next;
         fvg.lower     = h_prev;
         fvg.isBullish = true;
         fvg.time      = iTime(_Symbol, PERIOD_H1, i);
         fvg.filled    = false;
         int sz = ArraySize(fvgs);
         ArrayResize(fvgs, sz + 1);
         fvgs[sz] = fvg;
      }}

      // Bearish FVG
      if(h_next < l_prev && (l_prev - h_next) >= minSize)
      {{
         FVG fvg;
         fvg.upper     = l_prev;
         fvg.lower     = h_next;
         fvg.isBullish = false;
         fvg.time      = iTime(_Symbol, PERIOD_H1, i);
         fvg.filled    = false;
         int sz = ArraySize(fvgs);
         ArrayResize(fvgs, sz + 1);
         fvgs[sz] = fvg;
      }}
   }}
}}

//+------------------------------------------------------------------+
void CheckEntrySignals()
{{
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   // Check bullish OB entries (price returns to OB)
   for(int i = 0; i < ArraySize(bullishOBs); i++)
   {{
      if(bullishOBs[i].mitigated) continue;
      if(ask >= bullishOBs[i].low && ask <= bullishOBs[i].high)
      {{
         if(!InpUseMSS || IsBullishMSS())
         {{
            OpenBuy(bullishOBs[i].low - InpStopLoss * _Point * 10);
            bullishOBs[i].mitigated = true;
            return;
         }}
      }}
   }}

   // Check bearish OB entries
   for(int i = 0; i < ArraySize(bearishOBs); i++)
   {{
      if(bearishOBs[i].mitigated) continue;
      if(bid >= bearishOBs[i].low && bid <= bearishOBs[i].high)
      {{
         if(!InpUseMSS || IsBearishMSS())
         {{
            OpenSell(bearishOBs[i].high + InpStopLoss * _Point * 10);
            bearishOBs[i].mitigated = true;
            return;
         }}
      }}
   }}
}}

//+------------------------------------------------------------------+
bool IsBullishMSS()
{{
   // Higher high + higher low structure on H1
   double hh1 = iHigh(_Symbol, PERIOD_H1, 2);
   double hh2 = iHigh(_Symbol, PERIOD_H1, 4);
   double hl1 = iLow (_Symbol, PERIOD_H1, 2);
   double hl2 = iLow (_Symbol, PERIOD_H1, 4);
   return hh1 > hh2 && hl1 > hl2;
}}

//+------------------------------------------------------------------+
bool IsBearishMSS()
{{
   double lh1 = iHigh(_Symbol, PERIOD_H1, 2);
   double lh2 = iHigh(_Symbol, PERIOD_H1, 4);
   double ll1 = iLow (_Symbol, PERIOD_H1, 2);
   double ll2 = iLow (_Symbol, PERIOD_H1, 4);
   return lh1 < lh2 && ll1 < ll2;
}}

//+------------------------------------------------------------------+
bool IsKillzone()
{{
   MqlDateTime t;
   TimeToStruct(TimeGMT(), t);
   int hour = t.hour;
   // London open (7-9), New York open (12-14), London close (15-17)
   return (hour >= 7 && hour < 9) || (hour >= 12 && hour < 14) || (hour >= 15 && hour < 17);
}}

//+------------------------------------------------------------------+
void OpenBuy(double sl)
{{
   double ask  = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double tp   = ask + InpTakeProfit * _Point * 10;
   double lots = CalculateLots(MathAbs(ask - sl));
   if(lots <= 0) return;
   if(!Trade.Buy(lots, _Symbol, ask, sl, tp, InpComment))
      Print("ICT Buy error: ", Trade.ResultRetcodeDescription());
}}

//+------------------------------------------------------------------+
void OpenSell(double sl)
{{
   double bid  = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double tp   = bid - InpTakeProfit * _Point * 10;
   double lots = CalculateLots(MathAbs(sl - bid));
   if(lots <= 0) return;
   if(!Trade.Sell(lots, _Symbol, bid, sl, tp, InpComment))
      Print("ICT Sell error: ", Trade.ResultRetcodeDescription());
}}

//+------------------------------------------------------------------+
void ManagePositions()
{{
   if(!InpUseTrailing) return;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      if(!PositionInfo.SelectByIndex(i)) continue;
      if(PositionInfo.Symbol() != _Symbol || PositionInfo.Magic() != InpMagicNumber) continue;
      double open  = PositionInfo.PriceOpen();
      double curSL = PositionInfo.StopLoss();
      double curTP = PositionInfo.TakeProfit();
      double ask   = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double bid   = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      double start = InpTrailingStart * _Point * 10;
      double step  = InpTrailingStep  * _Point * 10;

      if(PositionInfo.PositionType() == POSITION_TYPE_BUY)
      {{
         if(bid - open < start) continue;
         double newSL = bid - step;
         if(newSL > curSL + step) Trade.PositionModify(PositionInfo.Ticket(), newSL, curTP);
      }}
      else
      {{
         if(open - ask < start) continue;
         double newSL = ask + step;
         if(curSL == 0 || newSL < curSL - step) Trade.PositionModify(PositionInfo.Ticket(), newSL, curTP);
      }}
   }}
}}

//+------------------------------------------------------------------+
double CalculateLots(double slDist)
{{
   double balance  = AccountInfo.Balance();
   double risk     = balance * InpRiskPercent / 100.0;
   double tickVal  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickSize == 0 || tickVal == 0 || slDist == 0) return 0;
   double lots    = risk / (slDist / tickSize * tickVal);
   double minLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lots = MathFloor(lots / lotStep) * lotStep;
   return MathMax(minLot, MathMin(maxLot, lots));
}}

//+------------------------------------------------------------------+
int CountPositions()
{{
   int cnt = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
      if(PositionInfo.SelectByIndex(i) &&
         PositionInfo.Symbol() == _Symbol &&
         PositionInfo.Magic()  == InpMagicNumber) cnt++;
   return cnt;
}}
'''

    def generate_trend_following_ea(self, name: str) -> str:
        """Generate trend following EA with EMA crossover"""
        return f'''//+------------------------------------------------------------------+
//| {name}.mq5                                                        |
//| JARVIS AI Trading System - Trend Following                       |
//+------------------------------------------------------------------+
#property copyright "JARVIS AI"
#property version   "1.00"
#property strict

#include <Trade\\Trade.mqh>
#include <Trade\\PositionInfo.mqh>
#include <Trade\\AccountInfo.mqh>

input group "=== Trading Settings ==="
input double InpRiskPercent  = 2.0;
input int    InpMagicNumber  = 33001;
input string InpComment      = "JARVIS_TREND";

input group "=== EMA Settings ==="
input int    InpEMAFast      = 21;
input int    InpEMASlow      = 55;
input int    InpEMAFilter    = 200;
input ENUM_TIMEFRAMES InpHTF = PERIOD_H4;

input group "=== ADX Filter ==="
input int    InpADXPeriod    = 14;
input double InpADXMin       = 25.0;

input group "=== Risk Settings ==="
input int    InpStopLoss     = 50;
input int    InpTakeProfit   = 150;
input bool   InpUseTrailing  = true;
input int    InpTrailingStart= 50;
input int    InpTrailingStep = 15;

CTrade        Trade;
CPositionInfo PositionInfo;
CAccountInfo  AccountInfo;

int      handleFast, handleSlow, handleFilter, handleADX;
datetime lastBar = 0;
bool     lastBullish = false;

//+------------------------------------------------------------------+
int OnInit()
{{
   Trade.SetExpertMagicNumber(InpMagicNumber);
   Trade.SetDeviationInPoints(20);

   handleFast   = iMA(_Symbol, PERIOD_H1, InpEMAFast,   0, MODE_EMA, PRICE_CLOSE);
   handleSlow   = iMA(_Symbol, PERIOD_H1, InpEMASlow,   0, MODE_EMA, PRICE_CLOSE);
   handleFilter = iMA(_Symbol, InpHTF,    InpEMAFilter, 0, MODE_EMA, PRICE_CLOSE);
   handleADX    = iADX(_Symbol, PERIOD_H1, InpADXPeriod);

   if(handleFast == INVALID_HANDLE || handleSlow   == INVALID_HANDLE ||
      handleFilter == INVALID_HANDLE || handleADX  == INVALID_HANDLE)
   {{
      Print("Handle error: ", GetLastError());
      return INIT_FAILED;
   }}
   Print("{name} initialised.");
   return INIT_SUCCEEDED;
}}

//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{{
   IndicatorRelease(handleFast);
   IndicatorRelease(handleSlow);
   IndicatorRelease(handleFilter);
   IndicatorRelease(handleADX);
}}

//+------------------------------------------------------------------+
void OnTick()
{{
   datetime cb = iTime(_Symbol, PERIOD_H1, 0);
   if(cb == lastBar) return;
   lastBar = cb;

   if(!TerminalInfoInteger(TERMINAL_TRADE_ALLOWED)) return;

   double fast[3], slow[3], filter[2], adxMain[2];
   if(CopyBuffer(handleFast,   0, 1, 3, fast)   < 3) return;
   if(CopyBuffer(handleSlow,   0, 1, 3, slow)   < 3) return;
   if(CopyBuffer(handleFilter, 0, 1, 2, filter) < 2) return;
   if(CopyBuffer(handleADX,    0, 1, 2, adxMain)< 2) return;

   double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   bool   aboveFilter = price > filter[0];
   bool   adxOk       = adxMain[0] >= InpADXMin;

   ManagePositions();

   // Golden cross: fast crosses above slow
   bool goldenCross = fast[0] > slow[0] && fast[1] <= slow[1];
   // Death cross: fast crosses below slow
   bool deathCross  = fast[0] < slow[0] && fast[1] >= slow[1];

   if(CountPositions() > 0) return;

   if(goldenCross && aboveFilter && adxOk) OpenBuy();
   if(deathCross  && !aboveFilter && adxOk) OpenSell();
}}

//+------------------------------------------------------------------+
void OpenBuy()
{{
   double ask  = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double sl   = ask - InpStopLoss   * _Point * 10;
   double tp   = ask + InpTakeProfit * _Point * 10;
   double lots = CalculateLots(InpStopLoss * _Point * 10);
   if(lots <= 0) return;
   Trade.Buy(lots, _Symbol, ask, sl, tp, InpComment);
}}

//+------------------------------------------------------------------+
void OpenSell()
{{
   double bid  = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl   = bid + InpStopLoss   * _Point * 10;
   double tp   = bid - InpTakeProfit * _Point * 10;
   double lots = CalculateLots(InpStopLoss * _Point * 10);
   if(lots <= 0) return;
   Trade.Sell(lots, _Symbol, bid, sl, tp, InpComment);
}}

//+------------------------------------------------------------------+
void ManagePositions()
{{
   if(!InpUseTrailing) return;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      if(!PositionInfo.SelectByIndex(i)) continue;
      if(PositionInfo.Symbol() != _Symbol || PositionInfo.Magic() != InpMagicNumber) continue;
      double open  = PositionInfo.PriceOpen();
      double curSL = PositionInfo.StopLoss();
      double curTP = PositionInfo.TakeProfit();
      double ask   = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double bid   = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      double start = InpTrailingStart * _Point * 10;
      double step  = InpTrailingStep  * _Point * 10;
      if(PositionInfo.PositionType() == POSITION_TYPE_BUY)
      {{
         if(bid - open < start) continue;
         double newSL = bid - step;
         if(newSL > curSL + step) Trade.PositionModify(PositionInfo.Ticket(), newSL, curTP);
      }}
      else
      {{
         if(open - ask < start) continue;
         double newSL = ask + step;
         if(curSL == 0 || newSL < curSL - step) Trade.PositionModify(PositionInfo.Ticket(), newSL, curTP);
      }}
   }}
}}

//+------------------------------------------------------------------+
double CalculateLots(double slDist)
{{
   double balance  = AccountInfo.Balance();
   double risk     = balance * InpRiskPercent / 100.0;
   double tickVal  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickSize == 0 || tickVal == 0 || slDist == 0) return 0;
   double lots    = risk / (slDist / tickSize * tickVal);
   double minLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lots = MathFloor(lots / lotStep) * lotStep;
   return MathMax(minLot, MathMin(maxLot, lots));
}}

//+------------------------------------------------------------------+
int CountPositions()
{{
   int cnt = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
      if(PositionInfo.SelectByIndex(i) &&
         PositionInfo.Symbol() == _Symbol &&
         PositionInfo.Magic()  == InpMagicNumber) cnt++;
   return cnt;
}}
'''

    def generate_mean_reversion_ea(self, name: str) -> str:
        """Generate mean reversion EA with Bollinger Bands"""
        return f'''//+------------------------------------------------------------------+
//| {name}.mq5                                                        |
//| JARVIS AI Trading System - Mean Reversion                        |
//+------------------------------------------------------------------+
#property copyright "JARVIS AI"
#property version   "1.00"
#property strict

#include <Trade\\Trade.mqh>
#include <Trade\\PositionInfo.mqh>
#include <Trade\\AccountInfo.mqh>

input group "=== Trading Settings ==="
input double InpRiskPercent  = 1.5;
input int    InpMagicNumber  = 44001;
input string InpComment      = "JARVIS_MR";

input group "=== Bollinger Bands ==="
input int    InpBBPeriod     = 20;
input double InpBBDeviation  = 2.0;
input double InpBBDevEntry   = 2.0;
input double InpBBDevExit    = 0.5;

input group "=== RSI Confirmation ==="
input int    InpRSIPeriod    = 14;
input double InpRSIOversold  = 35.0;
input double InpRSIOverbought= 65.0;

input group "=== ATR Volatility Filter ==="
input int    InpATRPeriod    = 14;
input double InpATRMultMin   = 0.5;
input double InpATRMultMax   = 3.0;

input group "=== Risk Settings ==="
input int    InpStopLoss     = 40;
input int    InpTakeProfit   = 40;
input bool   InpUseMidExit   = true;

CTrade        Trade;
CPositionInfo PositionInfo;
CAccountInfo  AccountInfo;

int      handleBB, handleRSI, handleATR;
datetime lastBar = 0;

//+------------------------------------------------------------------+
int OnInit()
{{
   Trade.SetExpertMagicNumber(InpMagicNumber);
   Trade.SetDeviationInPoints(20);

   handleBB  = iBands(_Symbol, PERIOD_H1, InpBBPeriod, 0, InpBBDeviation, PRICE_CLOSE);
   handleRSI = iRSI  (_Symbol, PERIOD_H1, InpRSIPeriod, PRICE_CLOSE);
   handleATR = iATR  (_Symbol, PERIOD_H1, InpATRPeriod);

   if(handleBB == INVALID_HANDLE || handleRSI == INVALID_HANDLE || handleATR == INVALID_HANDLE)
   {{
      Print("Handle error: ", GetLastError());
      return INIT_FAILED;
   }}
   Print("{name} initialised.");
   return INIT_SUCCEEDED;
}}

//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{{
   IndicatorRelease(handleBB);
   IndicatorRelease(handleRSI);
   IndicatorRelease(handleATR);
}}

//+------------------------------------------------------------------+
void OnTick()
{{
   datetime cb = iTime(_Symbol, PERIOD_H1, 0);
   if(cb == lastBar) return;
   lastBar = cb;

   if(!TerminalInfoInteger(TERMINAL_TRADE_ALLOWED)) return;

   double bbUpper[2], bbLower[2], bbMid[2], rsi[2], atr[2];
   if(CopyBuffer(handleBB,  1, 1, 2, bbUpper) < 2) return;
   if(CopyBuffer(handleBB,  2, 1, 2, bbLower) < 2) return;
   if(CopyBuffer(handleBB,  0, 1, 2, bbMid)   < 2) return;
   if(CopyBuffer(handleRSI, 0, 1, 2, rsi)     < 2) return;
   if(CopyBuffer(handleATR, 0, 1, 2, atr)     < 2) return;

   double close = iClose(_Symbol, PERIOD_H1, 1);
   double atrVal = atr[0];
   double bbWidth = bbUpper[0] - bbLower[0];

   if(!IsVolatilityOk(atrVal)) return;

   ManagePositions(bbMid[0]);

   if(CountPositions() > 0) return;

   bool buySignal  = close < bbLower[0] && rsi[0] < InpRSIOversold;
   bool sellSignal = close > bbUpper[0] && rsi[0] > InpRSIOverbought;

   if(buySignal)  OpenBuy();
   if(sellSignal) OpenSell();
}}

//+------------------------------------------------------------------+
void OpenBuy()
{{
   double ask  = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double sl   = ask - InpStopLoss   * _Point * 10;
   double tp   = ask + InpTakeProfit * _Point * 10;
   double lots = CalculateLots(InpStopLoss * _Point * 10);
   if(lots <= 0) return;
   Trade.Buy(lots, _Symbol, ask, sl, tp, InpComment);
}}

//+------------------------------------------------------------------+
void OpenSell()
{{
   double bid  = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl   = bid + InpStopLoss   * _Point * 10;
   double tp   = bid - InpTakeProfit * _Point * 10;
   double lots = CalculateLots(InpStopLoss * _Point * 10);
   if(lots <= 0) return;
   Trade.Sell(lots, _Symbol, bid, sl, tp, InpComment);
}}

//+------------------------------------------------------------------+
void ManagePositions(double midBand)
{{
   if(!InpUseMidExit) return;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      if(!PositionInfo.SelectByIndex(i)) continue;
      if(PositionInfo.Symbol() != _Symbol || PositionInfo.Magic() != InpMagicNumber) continue;
      double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      if(PositionInfo.PositionType() == POSITION_TYPE_BUY && bid >= midBand)
         Trade.PositionClose(PositionInfo.Ticket());
      if(PositionInfo.PositionType() == POSITION_TYPE_SELL && ask <= midBand)
         Trade.PositionClose(PositionInfo.Ticket());
   }}
}}

//+------------------------------------------------------------------+
bool IsVolatilityOk(double atrVal)
{{
   double bbUpper[1], bbLower[1];
   CopyBuffer(handleBB, 1, 1, 1, bbUpper);
   CopyBuffer(handleBB, 2, 1, 1, bbLower);
   double bandwidth = (bbUpper[0] - bbLower[0]) / atrVal;
   return bandwidth >= InpATRMultMin && bandwidth <= InpATRMultMax;
}}

//+------------------------------------------------------------------+
double CalculateLots(double slDist)
{{
   double balance  = AccountInfo.Balance();
   double risk     = balance * InpRiskPercent / 100.0;
   double tickVal  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickSize == 0 || tickVal == 0 || slDist == 0) return 0;
   double lots    = risk / (slDist / tickSize * tickVal);
   double minLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lots = MathFloor(lots / lotStep) * lotStep;
   return MathMax(minLot, MathMin(maxLot, lots));
}}

//+------------------------------------------------------------------+
int CountPositions()
{{
   int cnt = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
      if(PositionInfo.SelectByIndex(i) &&
         PositionInfo.Symbol() == _Symbol &&
         PositionInfo.Magic()  == InpMagicNumber) cnt++;
   return cnt;
}}
'''

    def generate_breakout_ea(self, name: str) -> str:
        """Generate breakout EA based on London session high/low"""
        return f'''//+------------------------------------------------------------------+
//| {name}.mq5                                                        |
//| JARVIS AI Trading System - Breakout Strategy                     |
//+------------------------------------------------------------------+
#property copyright "JARVIS AI"
#property version   "1.00"
#property strict

#include <Trade\\Trade.mqh>
#include <Trade\\PositionInfo.mqh>
#include <Trade\\AccountInfo.mqh>

input group "=== Trading Settings ==="
input double InpRiskPercent   = 1.5;
input int    InpMagicNumber   = 55001;
input string InpComment       = "JARVIS_BREAKOUT";

input group "=== Breakout Settings ==="
input int    InpRangeBars     = 20;      // Bars to calculate range
input double InpBreakoutBuffer= 3.0;    // Buffer in pips beyond range
input bool   InpLondonBreakout= true;   // Use London open breakout
input int    InpLondonOpenHour = 7;     // London open (GMT)
input int    InpRangeEndHour  = 9;      // Range calculation end (GMT)

input group "=== Volume Confirmation ==="
input bool   InpUseVolume     = true;
input double InpVolumeMinMult = 1.5;    // Minimum volume multiplier vs avg

input group "=== Risk Settings ==="
input int    InpStopLoss      = 40;
input int    InpTakeProfit    = 120;
input bool   InpUseTrailing   = true;
input int    InpTrailingStart = 40;
input int    InpTrailingStep  = 15;
input bool   InpBreakEven     = true;
input int    InpBEActivate    = 20;

CTrade        Trade;
CPositionInfo PositionInfo;
CAccountInfo  AccountInfo;

double   rangeHigh = 0, rangeLow = 0;
bool     rangeSet  = false;
bool     tradedToday = false;
datetime lastDay   = 0;
datetime lastBar   = 0;
int      handleATR;

//+------------------------------------------------------------------+
int OnInit()
{{
   Trade.SetExpertMagicNumber(InpMagicNumber);
   Trade.SetDeviationInPoints(20);
   handleATR = iATR(_Symbol, PERIOD_H1, 14);
   if(handleATR == INVALID_HANDLE) {{ Print("ATR handle error"); return INIT_FAILED; }}
   Print("{name} initialised.");
   return INIT_SUCCEEDED;
}}

//+------------------------------------------------------------------+
void OnDeinit(const int reason) {{ IndicatorRelease(handleATR); }}

//+------------------------------------------------------------------+
void OnTick()
{{
   datetime cb = iTime(_Symbol, PERIOD_H1, 0);
   if(cb == lastBar) return;
   lastBar = cb;

   MqlDateTime t;
   TimeToStruct(TimeGMT(), t);

   // Reset daily
   datetime today = StringToTime(TimeToString(TimeGMT(), TIME_DATE));
   if(today != lastDay)
   {{
      lastDay      = today;
      rangeSet     = false;
      tradedToday  = false;
      rangeHigh    = 0;
      rangeLow     = 0;
   }}

   if(!TerminalInfoInteger(TERMINAL_TRADE_ALLOWED)) return;

   // Calculate range during accumulation period
   if(InpLondonBreakout && t.hour >= InpLondonOpenHour && t.hour < InpRangeEndHour && !rangeSet)
      CalculateRange();

   // Look for breakout after range established
   if(rangeSet && !tradedToday && t.hour >= InpRangeEndHour && t.hour < 18)
   {{
      ManagePositions();
      if(CountPositions() > 0) return;
      CheckBreakout();
   }}
}}

//+------------------------------------------------------------------+
void CalculateRange()
{{
   int bars = InpRangeBars;
   rangeHigh = iHigh(_Symbol, PERIOD_H1, 1);
   rangeLow  = iLow (_Symbol, PERIOD_H1, 1);
   for(int i = 2; i <= bars; i++)
   {{
      double h = iHigh(_Symbol, PERIOD_H1, i);
      double l = iLow (_Symbol, PERIOD_H1, i);
      if(h > rangeHigh) rangeHigh = h;
      if(l < rangeLow)  rangeLow  = l;
   }}
   rangeSet = true;
   Print("Range set: H=", rangeHigh, " L=", rangeLow);
}}

//+------------------------------------------------------------------+
void CheckBreakout()
{{
   if(rangeHigh == 0 || rangeLow == 0) return;
   double buffer = InpBreakoutBuffer * _Point * 10;
   double ask    = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid    = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   if(!InpUseVolume || IsVolumeOk())
   {{
      if(ask > rangeHigh + buffer) {{ OpenBuy();  tradedToday = true; }}
      if(bid < rangeLow  - buffer) {{ OpenSell(); tradedToday = true; }}
   }}
}}

//+------------------------------------------------------------------+
bool IsVolumeOk()
{{
   long vol = iVolume(_Symbol, PERIOD_H1, 1);
   long avgVol = 0;
   for(int i = 2; i <= 21; i++) avgVol += iVolume(_Symbol, PERIOD_H1, i);
   avgVol /= 20;
   return avgVol > 0 && (double)vol >= avgVol * InpVolumeMinMult;
}}

//+------------------------------------------------------------------+
void OpenBuy()
{{
   double ask  = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double sl   = rangeLow  - InpStopLoss   * _Point * 10;
   double tp   = ask + InpTakeProfit * _Point * 10;
   double lots = CalculateLots(MathAbs(ask - sl));
   if(lots <= 0) return;
   Trade.Buy(lots, _Symbol, ask, sl, tp, InpComment);
}}

//+------------------------------------------------------------------+
void OpenSell()
{{
   double bid  = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl   = rangeHigh + InpStopLoss   * _Point * 10;
   double tp   = bid - InpTakeProfit * _Point * 10;
   double lots = CalculateLots(MathAbs(sl - bid));
   if(lots <= 0) return;
   Trade.Sell(lots, _Symbol, bid, sl, tp, InpComment);
}}

//+------------------------------------------------------------------+
void ManagePositions()
{{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      if(!PositionInfo.SelectByIndex(i)) continue;
      if(PositionInfo.Symbol() != _Symbol || PositionInfo.Magic() != InpMagicNumber) continue;

      ulong  ticket = PositionInfo.Ticket();
      double open   = PositionInfo.PriceOpen();
      double curSL  = PositionInfo.StopLoss();
      double curTP  = PositionInfo.TakeProfit();
      double ask    = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double bid    = SymbolInfoDouble(_Symbol, SYMBOL_BID);

      // Break-even
      if(InpBreakEven)
      {{
         double beActivate = InpBEActivate * _Point * 10;
         if(PositionInfo.PositionType() == POSITION_TYPE_BUY)
         {{
            if(bid - open >= beActivate && curSL < open)
               Trade.PositionModify(ticket, open + _Point, curTP);
         }}
         else
         {{
            if(open - ask >= beActivate && (curSL > open || curSL == 0))
               Trade.PositionModify(ticket, open - _Point, curTP);
         }}
      }}

      // Trailing
      if(InpUseTrailing)
      {{
         double start = InpTrailingStart * _Point * 10;
         double step  = InpTrailingStep  * _Point * 10;
         if(PositionInfo.PositionType() == POSITION_TYPE_BUY)
         {{
            if(bid - open < start) continue;
            double newSL = bid - step;
            if(newSL > curSL + step) Trade.PositionModify(ticket, newSL, curTP);
         }}
         else
         {{
            if(open - ask < start) continue;
            double newSL = ask + step;
            if(curSL == 0 || newSL < curSL - step) Trade.PositionModify(ticket, newSL, curTP);
         }}
      }}
   }}
}}

//+------------------------------------------------------------------+
double CalculateLots(double slDist)
{{
   double balance  = AccountInfo.Balance();
   double risk     = balance * InpRiskPercent / 100.0;
   double tickVal  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickSize == 0 || tickVal == 0 || slDist == 0) return 0;
   double lots    = risk / (slDist / tickSize * tickVal);
   double minLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lots = MathFloor(lots / lotStep) * lotStep;
   return MathMax(minLot, MathMin(maxLot, lots));
}}

//+------------------------------------------------------------------+
int CountPositions()
{{
   int cnt = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
      if(PositionInfo.SelectByIndex(i) &&
         PositionInfo.Symbol() == _Symbol &&
         PositionInfo.Magic()  == InpMagicNumber) cnt++;
   return cnt;
}}
'''

    # ------------------------------------------------------------------
    # Include file generators
    # ------------------------------------------------------------------

    def generate_news_filter(self) -> str:
        """Generate MQL5 news filter include file"""
        return '''//+------------------------------------------------------------------+
//| NewsFilter.mqh                                                    |
//| JARVIS AI - News event filter                                     |
//+------------------------------------------------------------------+
#ifndef JARVIS_NEWS_FILTER_MQH
#define JARVIS_NEWS_FILTER_MQH

input group "=== News Filter ==="
input bool   NFInpEnabled         = true;
input int    NFInpMinutesBefore   = 30;
input int    NFInpMinutesAfter    = 30;
input bool   NFInpHighImpactOnly  = true;

struct NewsEvent
{
   datetime time;
   string   currency;
   string   title;
   int      impact;  // 1=Low 2=Medium 3=High
};

NewsEvent g_newsEvents[];
datetime  g_newsLastFetch = 0;

//+------------------------------------------------------------------+
bool IsNewsTime(string symbol = "")
{
   if(!NFInpEnabled) return false;

   datetime now = TimeCurrent();
   string cur1 = "", cur2 = "";

   if(symbol == "") symbol = _Symbol;
   if(StringLen(symbol) >= 6)
   {
      cur1 = StringSubstr(symbol, 0, 3);
      cur2 = StringSubstr(symbol, 3, 3);
   }

   for(int i = 0; i < ArraySize(g_newsEvents); i++)
   {
      NewsEvent& ev = g_newsEvents[i];
      if(NFInpHighImpactOnly && ev.impact < 3) continue;

      if(symbol != "" && ev.currency != cur1 && ev.currency != cur2) continue;

      datetime start = ev.time - NFInpMinutesBefore * 60;
      datetime end   = ev.time + NFInpMinutesAfter  * 60;

      if(now >= start && now <= end)
      {
         Print("News filter active: ", ev.title, " at ", TimeToString(ev.time));
         return true;
      }
   }
   return false;
}

//+------------------------------------------------------------------+
bool AddNewsEvent(datetime evTime, string currency, string title, int impact)
{
   int sz = ArraySize(g_newsEvents);
   ArrayResize(g_newsEvents, sz + 1);
   g_newsEvents[sz].time     = evTime;
   g_newsEvents[sz].currency = currency;
   g_newsEvents[sz].title    = title;
   g_newsEvents[sz].impact   = impact;
   return true;
}

//+------------------------------------------------------------------+
void ClearNewsEvents()
{
   ArrayFree(g_newsEvents);
}

//+------------------------------------------------------------------+
int CountUpcomingNews(int minutesAhead = 60)
{
   datetime now   = TimeCurrent();
   datetime limit = now + minutesAhead * 60;
   int count = 0;
   for(int i = 0; i < ArraySize(g_newsEvents); i++)
   {
      if(g_newsEvents[i].time >= now && g_newsEvents[i].time <= limit)
         count++;
   }
   return count;
}

#endif // JARVIS_NEWS_FILTER_MQH
'''

    def generate_risk_manager(self) -> str:
        """Generate MQL5 risk management include file"""
        return '''//+------------------------------------------------------------------+
//| RiskManager.mqh                                                   |
//| JARVIS AI - Risk management utilities                             |
//+------------------------------------------------------------------+
#ifndef JARVIS_RISK_MANAGER_MQH
#define JARVIS_RISK_MANAGER_MQH

#include <Trade\\AccountInfo.mqh>

input group "=== Risk Manager ==="
input double RMInpMaxDailyLoss      = 5.0;   // Max daily loss %
input double RMInpMaxWeeklyLoss     = 10.0;  // Max weekly loss %
input double RMInpMaxDrawdown       = 15.0;  // Max total drawdown %
input int    RMInpMaxPositions      = 5;     // Max concurrent positions
input double RMInpMaxLotSize        = 5.0;   // Max lot size
input bool   RMInpPropFirmMode      = false; // Prop firm rules

CAccountInfo g_rmAccount;

double g_rmDailyStartBalance   = 0;
double g_rmWeeklyStartBalance  = 0;
datetime g_rmLastDayCheck      = 0;
datetime g_rmLastWeekCheck     = 0;

//+------------------------------------------------------------------+
void RMInit()
{
   g_rmDailyStartBalance  = g_rmAccount.Balance();
   g_rmWeeklyStartBalance = g_rmAccount.Balance();
   g_rmLastDayCheck       = TimeCurrent();
   g_rmLastWeekCheck      = TimeCurrent();
}

//+------------------------------------------------------------------+
void RMUpdatePeriods()
{
   MqlDateTime now;
   TimeToStruct(TimeCurrent(), now);

   MqlDateTime last;
   TimeToStruct(g_rmLastDayCheck, last);

   if(now.day != last.day)
   {
      g_rmDailyStartBalance = g_rmAccount.Balance();
      g_rmLastDayCheck      = TimeCurrent();
   }

   TimeToStruct(g_rmLastWeekCheck, last);
   if(now.day_of_week < last.day_of_week || (now.day - last.day) >= 7)
   {
      g_rmWeeklyStartBalance = g_rmAccount.Balance();
      g_rmLastWeekCheck      = TimeCurrent();
   }
}

//+------------------------------------------------------------------+
bool RMIsTradeAllowed()
{
   RMUpdatePeriods();

   double balance   = g_rmAccount.Balance();
   double equity    = g_rmAccount.Equity();

   // Daily loss check
   if(g_rmDailyStartBalance > 0)
   {
      double dailyLossPct = (g_rmDailyStartBalance - equity) / g_rmDailyStartBalance * 100.0;
      if(dailyLossPct >= RMInpMaxDailyLoss)
      {
         Print("RiskManager: Daily loss limit reached (", DoubleToString(dailyLossPct,2), "%)");
         return false;
      }
   }

   // Weekly loss check
   if(g_rmWeeklyStartBalance > 0)
   {
      double weeklyLossPct = (g_rmWeeklyStartBalance - equity) / g_rmWeeklyStartBalance * 100.0;
      if(weeklyLossPct >= RMInpMaxWeeklyLoss)
      {
         Print("RiskManager: Weekly loss limit reached (", DoubleToString(weeklyLossPct,2), "%)");
         return false;
      }
   }

   // Drawdown check
   double startBalance = MathMax(g_rmDailyStartBalance, balance);
   if(startBalance > 0)
   {
      double ddPct = (startBalance - equity) / startBalance * 100.0;
      if(ddPct >= RMInpMaxDrawdown)
      {
         Print("RiskManager: Max drawdown reached (", DoubleToString(ddPct,2), "%)");
         return false;
      }
   }

   // Position count check
   if(PositionsTotal() >= RMInpMaxPositions)
   {
      Print("RiskManager: Max positions reached (", PositionsTotal(), ")");
      return false;
   }

   return true;
}

//+------------------------------------------------------------------+
double RMCalculateLots(string symbol, double slDistance, double riskPct)
{
   double balance  = g_rmAccount.Balance();
   double risk     = balance * riskPct / 100.0;
   double tickVal  = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_SIZE);

   if(tickSize == 0 || tickVal == 0 || slDistance == 0) return 0;

   double lots    = risk / (slDistance / tickSize * tickVal);
   double minLot  = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MIN);
   double maxLot  = MathMin(SymbolInfoDouble(symbol, SYMBOL_VOLUME_MAX), RMInpMaxLotSize);
   double lotStep = SymbolInfoDouble(symbol, SYMBOL_VOLUME_STEP);

   lots = MathFloor(lots / lotStep) * lotStep;
   return MathMax(minLot, MathMin(maxLot, lots));
}

//+------------------------------------------------------------------+
double RMGetDailyPnL()
{
   return g_rmAccount.Equity() - g_rmDailyStartBalance;
}

//+------------------------------------------------------------------+
double RMGetCurrentDrawdown()
{
   double equity   = g_rmAccount.Equity();
   double balance  = g_rmAccount.Balance();
   double peak     = MathMax(balance, g_rmWeeklyStartBalance);
   if(peak <= 0) return 0;
   return (peak - equity) / peak * 100.0;
}

#endif // JARVIS_RISK_MANAGER_MQH
'''

    def generate_trailing_stop(self) -> str:
        """Generate MQL5 trailing stop include file"""
        return '''//+------------------------------------------------------------------+
//| TrailingStop.mqh                                                  |
//| JARVIS AI - Advanced trailing stop implementations               |
//+------------------------------------------------------------------+
#ifndef JARVIS_TRAILING_STOP_MQH
#define JARVIS_TRAILING_STOP_MQH

#include <Trade\\Trade.mqh>
#include <Trade\\PositionInfo.mqh>

CTrade        g_tsTrade;
CPositionInfo g_tsPosition;

enum ENUM_TRAILING_TYPE
{
   TRAILING_FIXED     = 0,  // Fixed pip distance
   TRAILING_ATR       = 1,  // ATR-based
   TRAILING_PARABOLIC = 2,  // Parabolic SAR style
   TRAILING_CHANDELIER= 3   // Chandelier exit
};

//+------------------------------------------------------------------+
// Fixed-distance trailing stop
//+------------------------------------------------------------------+
void ApplyFixedTrailing(ulong ticket, int startPips, int stepPips, int magicNumber)
{
   if(!g_tsPosition.SelectByTicket(ticket)) return;
   if(g_tsPosition.Magic() != magicNumber) return;

   string symbol  = g_tsPosition.Symbol();
   double open    = g_tsPosition.PriceOpen();
   double curSL   = g_tsPosition.StopLoss();
   double curTP   = g_tsPosition.TakeProfit();
   double point   = SymbolInfoDouble(symbol, SYMBOL_POINT);
   double start   = startPips * point * 10;
   double step    = stepPips  * point * 10;

   if(g_tsPosition.PositionType() == POSITION_TYPE_BUY)
   {
      double bid = SymbolInfoDouble(symbol, SYMBOL_BID);
      if(bid - open < start) return;
      double newSL = bid - step;
      if(newSL > curSL + point)
         g_tsTrade.PositionModify(ticket, newSL, curTP);
   }
   else
   {
      double ask = SymbolInfoDouble(symbol, SYMBOL_ASK);
      if(open - ask < start) return;
      double newSL = ask + step;
      if(curSL == 0 || newSL < curSL - point)
         g_tsTrade.PositionModify(ticket, newSL, curTP);
   }
}

//+------------------------------------------------------------------+
// ATR-based trailing stop
//+------------------------------------------------------------------+
void ApplyATRTrailing(ulong ticket, int atrHandle, double atrMultiplier,
                      int startPips, int magicNumber)
{
   if(!g_tsPosition.SelectByTicket(ticket)) return;
   if(g_tsPosition.Magic() != magicNumber) return;

   string symbol = g_tsPosition.Symbol();
   double open   = g_tsPosition.PriceOpen();
   double curSL  = g_tsPosition.StopLoss();
   double curTP  = g_tsPosition.TakeProfit();
   double point  = SymbolInfoDouble(symbol, SYMBOL_POINT);
   double start  = startPips * point * 10;

   double atrBuf[1];
   if(CopyBuffer(atrHandle, 0, 1, 1, atrBuf) < 1) return;
   double atrDist = atrBuf[0] * atrMultiplier;

   if(g_tsPosition.PositionType() == POSITION_TYPE_BUY)
   {
      double bid = SymbolInfoDouble(symbol, SYMBOL_BID);
      if(bid - open < start) return;
      double newSL = bid - atrDist;
      if(newSL > curSL + point)
         g_tsTrade.PositionModify(ticket, newSL, curTP);
   }
   else
   {
      double ask = SymbolInfoDouble(symbol, SYMBOL_ASK);
      if(open - ask < start) return;
      double newSL = ask + atrDist;
      if(curSL == 0 || newSL < curSL - point)
         g_tsTrade.PositionModify(ticket, newSL, curTP);
   }
}

//+------------------------------------------------------------------+
// Chandelier exit trailing stop
//+------------------------------------------------------------------+
void ApplyChandelierTrailing(ulong ticket, int lookback, double atrMult,
                              int atrHandle, int magicNumber)
{
   if(!g_tsPosition.SelectByTicket(ticket)) return;
   if(g_tsPosition.Magic() != magicNumber) return;

   string symbol = g_tsPosition.Symbol();
   double curSL  = g_tsPosition.StopLoss();
   double curTP  = g_tsPosition.TakeProfit();
   double point  = SymbolInfoDouble(symbol, SYMBOL_POINT);

   double atrBuf[1];
   if(CopyBuffer(atrHandle, 0, 1, 1, atrBuf) < 1) return;
   double atrVal = atrBuf[0] * atrMult;

   if(g_tsPosition.PositionType() == POSITION_TYPE_BUY)
   {
      // Chandelier long: highest high over lookback - ATR * mult
      double highest = iHigh(symbol, PERIOD_CURRENT, iHighest(symbol, PERIOD_CURRENT, MODE_HIGH, lookback, 1));
      double newSL   = highest - atrVal;
      if(newSL > curSL + point)
         g_tsTrade.PositionModify(ticket, newSL, curTP);
   }
   else
   {
      double lowest = iLow(symbol, PERIOD_CURRENT, iLowest(symbol, PERIOD_CURRENT, MODE_LOW, lookback, 1));
      double newSL  = lowest + atrVal;
      if(curSL == 0 || newSL < curSL - point)
         g_tsTrade.PositionModify(ticket, newSL, curTP);
   }
}

//+------------------------------------------------------------------+
// Move to break-even
//+------------------------------------------------------------------+
bool MoveToBreakEven(ulong ticket, int activatePips, int lockInPips, int magicNumber)
{
   if(!g_tsPosition.SelectByTicket(ticket)) return false;
   if(g_tsPosition.Magic() != magicNumber) return false;

   string symbol   = g_tsPosition.Symbol();
   double open     = g_tsPosition.PriceOpen();
   double curSL    = g_tsPosition.StopLoss();
   double curTP    = g_tsPosition.TakeProfit();
   double point    = SymbolInfoDouble(symbol, SYMBOL_POINT);
   double activate = activatePips * point * 10;
   double lockIn   = lockInPips   * point * 10;

   if(g_tsPosition.PositionType() == POSITION_TYPE_BUY)
   {
      double bid = SymbolInfoDouble(symbol, SYMBOL_BID);
      if(bid - open >= activate && curSL < open + lockIn)
      {
         g_tsTrade.PositionModify(ticket, open + lockIn, curTP);
         return true;
      }
   }
   else
   {
      double ask = SymbolInfoDouble(symbol, SYMBOL_ASK);
      if(open - ask >= activate && (curSL > open - lockIn || curSL == 0))
      {
         g_tsTrade.PositionModify(ticket, open - lockIn, curTP);
         return true;
      }
   }
   return false;
}

#endif // JARVIS_TRAILING_STOP_MQH
'''

    def generate_custom_indicator(self, config: Dict) -> str:
        """Generate a custom MQL5 indicator from config dict.

        Config keys:
            name        – indicator name
            buffers     – list of dicts: {name, color, style, width}
            period      – default calculation period
            price_type  – "CLOSE" | "OPEN" | "HIGH" | "LOW" | "HL2"
        """
        name = config.get("name", "JARVIS_Indicator")
        period = config.get("period", 14)
        price_type = config.get("price_type", "CLOSE")
        buffers_cfg = config.get("buffers", [
            {"name": "MainBuffer", "color": "clrDodgerBlue", "style": "STYLE_SOLID", "width": 2}
        ])

        n_buffers = len(buffers_cfg)
        buf_props = "\n".join(
            f'#property indicator_color{i+1} {b.get("color","clrDodgerBlue")}\n'
            f'#property indicator_style{i+1} {b.get("style","STYLE_SOLID")}\n'
            f'#property indicator_width{i+1} {b.get("width",1)}'
            for i, b in enumerate(buffers_cfg)
        )

        buf_decls = "\n".join(f'double {b["name"]}[];' for b in buffers_cfg)
        buf_setindex = "\n   ".join(
            f'SetIndexBuffer({i}, {b["name"]}, INDICATOR_DATA);\n   '
            f'PlotIndexSetString({i}, PLOT_LABEL, "{b["name"]}");'
            for i, b in enumerate(buffers_cfg)
        )

        main_buf = buffers_cfg[0]["name"]
        price_enum = f"PRICE_{price_type}"

        return f'''//+------------------------------------------------------------------+
//| {name}.mq5                                                        |
//| JARVIS AI Trading System - Custom Indicator                      |
//+------------------------------------------------------------------+
#property copyright   "JARVIS AI"
#property version     "1.00"
#property indicator_chart_window
#property indicator_buffers {n_buffers}
#property indicator_plots   {n_buffers}
{buf_props}

input int    InpPeriod     = {period};
input ENUM_APPLIED_PRICE InpPrice = {price_enum};

{buf_decls}
int handleMA;

//+------------------------------------------------------------------+
int OnInit()
{{
   {buf_setindex}
   handleMA = iMA(_Symbol, PERIOD_CURRENT, InpPeriod, 0, MODE_EMA, InpPrice);
   if(handleMA == INVALID_HANDLE) {{ Print("Handle error"); return INIT_FAILED; }}
   IndicatorSetString(INDICATOR_SHORTNAME, "{name}(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}}

//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{{
   IndicatorRelease(handleMA);
}}

//+------------------------------------------------------------------+
int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double   &open[],
                const double   &high[],
                const double   &low[],
                const double   &close[],
                const long     &tick_volume[],
                const long     &volume[],
                const int      &spread[])
{{
   if(rates_total < InpPeriod) return 0;

   int start = (prev_calculated > 0) ? prev_calculated - 1 : InpPeriod - 1;
   double maBuffer[];
   ArraySetAsSeries(maBuffer, false);

   if(CopyBuffer(handleMA, 0, 0, rates_total, maBuffer) < rates_total) return prev_calculated;

   for(int i = start; i < rates_total; i++)
   {{
      {main_buf}[i] = maBuffer[i];
   }}

   return rates_total;
}}
'''

    # ------------------------------------------------------------------
    # Save utilities
    # ------------------------------------------------------------------

    def save_ea(self, name: str, content: str) -> Path:
        """Save EA content to generated/experts/<name>.mq5"""
        path = self.OUTPUT_DIR / "experts" / f"{name}.mq5"
        path.write_text(content, encoding="utf-8")
        logger.info(f"EA saved: {path}")
        return path

    def save_indicator(self, name: str, content: str) -> Path:
        """Save indicator content to generated/indicators/<name>.mq5"""
        path = self.OUTPUT_DIR / "indicators" / f"{name}.mq5"
        path.write_text(content, encoding="utf-8")
        logger.info(f"Indicator saved: {path}")
        return path

    def save_include(self, name: str, content: str) -> Path:
        """Save include content to generated/include/<name>.mqh"""
        path = self.OUTPUT_DIR / "include" / f"{name}.mqh"
        path.write_text(content, encoding="utf-8")
        logger.info(f"Include saved: {path}")
        return path

    def install_to_mt5(self, source: Path, mt5_path: str, file_type: str = "ea") -> bool:
        """Copy generated file to MT5 MQL5/Experts or MQL5/Indicators folder.

        Args:
            source:    Path to the .mq5 / .mqh file
            mt5_path:  Base MT5 installation directory
            file_type: "ea" | "indicator" | "include"
        """
        subfolder_map = {
            "ea":        "MQL5/Experts/JARVIS",
            "indicator": "MQL5/Indicators/JARVIS",
            "include":   "MQL5/Include/JARVIS",
        }
        subfolder = subfolder_map.get(file_type, "MQL5/Experts/JARVIS")
        dest_dir = Path(mt5_path) / subfolder
        dest_dir.mkdir(parents=True, exist_ok=True)
        dest = dest_dir / source.name
        try:
            shutil.copy2(source, dest)
            logger.info(f"Installed {source.name} → {dest}")
            return True
        except Exception as e:
            logger.error(f"Failed to install {source.name}: {e}")
            return False
