from dataclasses import dataclass


@dataclass(slots=True)
class MQL5TemplateRequest:
    name: str
    strategy_type: str
    include_trailing_stop: bool
    include_news_filter: bool


def render_expert_advisor(request: MQL5TemplateRequest) -> str:
    trailing_line = "   // trailing stop support enabled" if request.include_trailing_stop else ""
    news_filter_line = "   // news filter hooks enabled" if request.include_news_filter else ""

    return f"""#property strict

input double RiskPerTrade = 0.5;
input int StopLossPoints = 300;
input int TakeProfitPoints = 600;

int OnInit()
{{
   Print(\"{request.name} initialized for {request.strategy_type}\");
{trailing_line}
{news_filter_line}
   return(INIT_SUCCEEDED);
}}

void OnTick()
{{
   // Generated by JARVIS. Insert validated signal logic before live use.
}}
"""
