"""
jarvis_scrape_scraper
=====================
Auto-generated by J.A.R.V.I.S. Code-Forge on 2026-05-11T16:42:01.057184+00:00.

scrape latest crypto headlines
"""
from __future__ import annotations
import json, time
from pathlib import Path
import requests
from bs4 import BeautifulSoup


def scrape(url: str, timeout: float = 15.0) -> dict:
    r = requests.get(url, timeout=timeout, headers={"User-Agent": "JARVIS/1.0"})
    r.raise_for_status()
    soup = BeautifulSoup(r.text, "html.parser")
    return {
        "url": url,
        "title": (soup.title.string or "").strip() if soup.title else "",
        "len": len(r.text),
    }


def main() -> None:
    out = Path(__file__).with_suffix(".json")
    data = scrape("https://example.com")
    out.write_text(json.dumps(data, indent=2), encoding="utf-8")
    print("wrote", out)


if __name__ == "__main__":
    main()
