"""
jarvis_trade_dataclass
======================
Auto-generated by J.A.R.V.I.S. Code-Forge on 2026-05-11T16:42:01.170214+00:00.

trade order dataclass
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import List


@dataclass
class Item:
    name: str
    quantity: int = 1
    tags: List[str] = field(default_factory=list)


@dataclass
class Inventory:
    items: List[Item] = field(default_factory=list)

    def add(self, item: Item) -> None:
        self.items.append(item)

    def total(self) -> int:
        return sum(i.quantity for i in self.items)


if __name__ == "__main__":
    inv = Inventory()
    inv.add(Item("alpha", 3))
    inv.add(Item("beta", 7, tags=["new"]))
    print("total:", inv.total())
