"""
JARVIS AI Trading OS - Code Generator

Generates complete Python strategy files, MQL5 Expert Advisors, indicator files,
risk management configs, and utility modules from templates.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)


@dataclass
class GeneratedFile:
    path: str
    language: str
    description: str
    content: str
    created_at: datetime = field(default_factory=datetime.utcnow)


def _render(template: str, ctx: dict[str, Any]) -> str:
    """Simple Jinja2-style ``{{ key }}`` replacement without external deps."""
    result = template
    for key, value in ctx.items():
        result = result.replace("{{ " + key + " }}", str(value))
    return result


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

_PYTHON_STRATEGY_TEMPLATE = '''\
"""
Auto-generated {{ strategy_display }} strategy for {{ asset }}.
Generated by JARVIS AI Trading OS at {{ timestamp }}.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Optional

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


class Signal(Enum):
    BUY = auto()
    SELL = auto()
    HOLD = auto()


@dataclass
class TradeSetup:
    signal: Signal
    entry_price: float
    stop_loss: float
    take_profit: float
    lot_size: float = 0.01
    confidence: float = 0.0
    reason: str = ""


@dataclass
class StrategyConfig:
    symbol: str = "{{ asset }}"
    timeframe: str = "{{ timeframe }}"
    risk_per_trade: float = 0.02
    max_spread: float = 3.0
    sl_pips: float = {{ sl_pips }}
    tp_pips: float = {{ tp_pips }}
    fast_period: int = {{ fast_period }}
    slow_period: int = {{ slow_period }}
    atr_period: int = 14
    atr_multiplier: float = 1.5


class {{ class_name }}:
    """{{ strategy_display }} strategy implementation for {{ asset }}."""

    def __init__(self, config: Optional[StrategyConfig] = None) -> None:
        self.config = config or StrategyConfig()
        self._position_open = False
        self._last_signal = Signal.HOLD

    def calculate_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()
        df["ema_fast"] = df["close"].ewm(span=self.config.fast_period, adjust=False).mean()
        df["ema_slow"] = df["close"].ewm(span=self.config.slow_period, adjust=False).mean()
        df["atr"] = self._atr(df, self.config.atr_period)
        df["rsi"] = self._rsi(df["close"], 14)
        return df

    def generate_signal(self, df: pd.DataFrame) -> TradeSetup:
        df = self.calculate_indicators(df)
        latest = df.iloc[-1]
        prev = df.iloc[-2]

        if prev["ema_fast"] <= prev["ema_slow"] and latest["ema_fast"] > latest["ema_slow"]:
            if latest["rsi"] < 70:
                return self._create_setup(Signal.BUY, latest)

        if prev["ema_fast"] >= prev["ema_slow"] and latest["ema_fast"] < latest["ema_slow"]:
            if latest["rsi"] > 30:
                return self._create_setup(Signal.SELL, latest)

        return TradeSetup(signal=Signal.HOLD, entry_price=latest["close"], stop_loss=0.0, take_profit=0.0)

    def _create_setup(self, signal: Signal, bar: pd.Series) -> TradeSetup:
        pip = 0.0001 if "JPY" not in self.config.symbol else 0.01
        atr_sl = bar["atr"] * self.config.atr_multiplier

        if signal == Signal.BUY:
            sl = bar["close"] - max(atr_sl, self.config.sl_pips * pip)
            tp = bar["close"] + self.config.tp_pips * pip
        else:
            sl = bar["close"] + max(atr_sl, self.config.sl_pips * pip)
            tp = bar["close"] - self.config.tp_pips * pip

        return TradeSetup(
            signal=signal,
            entry_price=bar["close"],
            stop_loss=round(sl, 5),
            take_profit=round(tp, 5),
            lot_size=0.01,
            confidence=min(abs(bar["ema_fast"] - bar["ema_slow"]) / bar["atr"], 1.0) if bar["atr"] else 0.0,
            reason=f"EMA crossover with RSI confirmation (RSI={bar['rsi']:.1f})",
        )

    @staticmethod
    def _atr(df: pd.DataFrame, period: int) -> pd.Series:
        high_low = df["high"] - df["low"]
        high_close = (df["high"] - df["close"].shift()).abs()
        low_close = (df["low"] - df["close"].shift()).abs()
        tr = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)
        return tr.rolling(window=period).mean()

    @staticmethod
    def _rsi(series: pd.Series, period: int = 14) -> pd.Series:
        delta = series.diff()
        gain = delta.where(delta > 0, 0.0).rolling(window=period).mean()
        loss = (-delta.where(delta < 0, 0.0)).rolling(window=period).mean()
        rs = gain / loss.replace(0, np.nan)
        return 100.0 - (100.0 / (1.0 + rs))
'''

_MQL5_EA_TEMPLATE = '''\
//+------------------------------------------------------------------+
//| {{ ea_name }}.mq5                                                 |
//| Auto-generated by JARVIS AI Trading OS                            |
//| Generated: {{ timestamp }}                                        |
//+------------------------------------------------------------------+
#property copyright "JARVIS AI Trading OS"
#property version   "1.00"
#property strict

input string   InpSymbol       = "{{ asset }}";
input ENUM_TIMEFRAMES InpTimeframe = PERIOD_{{ timeframe_mql }};
input double   InpLotSize      = 0.01;
input double   InpSLPips       = {{ sl_pips }};
input double   InpTPPips       = {{ tp_pips }};
input int      InpFastPeriod   = {{ fast_period }};
input int      InpSlowPeriod   = {{ slow_period }};
input double   InpMaxSpread    = 3.0;
input double   InpRiskPercent  = 2.0;

int handleFast, handleSlow;
double bufFast[], bufSlow[];

int OnInit()
{
    handleFast = iMA(_Symbol, InpTimeframe, InpFastPeriod, 0, MODE_EMA, PRICE_CLOSE);
    handleSlow = iMA(_Symbol, InpTimeframe, InpSlowPeriod, 0, MODE_EMA, PRICE_CLOSE);
    if(handleFast == INVALID_HANDLE || handleSlow == INVALID_HANDLE)
    {
        Print("Failed to create indicator handles");
        return INIT_FAILED;
    }
    ArraySetAsSeries(bufFast, true);
    ArraySetAsSeries(bufSlow, true);
    return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
    IndicatorRelease(handleFast);
    IndicatorRelease(handleSlow);
}

void OnTick()
{
    if(!IsNewBar()) return;

    double spread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD) * _Point;
    if(spread > InpMaxSpread * _Point) return;

    if(CopyBuffer(handleFast, 0, 0, 3, bufFast) < 3) return;
    if(CopyBuffer(handleSlow, 0, 0, 3, bufSlow) < 3) return;

    bool crossUp   = bufFast[2] <= bufSlow[2] && bufFast[1] > bufSlow[1];
    bool crossDown = bufFast[2] >= bufSlow[2] && bufFast[1] < bufSlow[1];

    if(PositionsTotal() == 0)
    {
        if(crossUp)
            OpenTrade(ORDER_TYPE_BUY);
        else if(crossDown)
            OpenTrade(ORDER_TYPE_SELL);
    }
}

void OpenTrade(ENUM_ORDER_TYPE type)
{
    MqlTradeRequest request = {};
    MqlTradeResult  result  = {};
    double price = (type == ORDER_TYPE_BUY) ? SymbolInfoDouble(_Symbol, SYMBOL_ASK)
                                             : SymbolInfoDouble(_Symbol, SYMBOL_BID);
    double pip = (_Digits == 5 || _Digits == 3) ? _Point * 10 : _Point;
    double sl  = (type == ORDER_TYPE_BUY) ? price - InpSLPips * pip
                                           : price + InpSLPips * pip;
    double tp  = (type == ORDER_TYPE_BUY) ? price + InpTPPips * pip
                                           : price - InpTPPips * pip;
    request.action   = TRADE_ACTION_DEAL;
    request.symbol   = _Symbol;
    request.volume   = InpLotSize;
    request.type     = type;
    request.price    = price;
    request.sl       = NormalizeDouble(sl, _Digits);
    request.tp       = NormalizeDouble(tp, _Digits);
    request.deviation= 10;
    request.magic    = 123456;
    request.comment  = "JARVIS {{ strategy_display }}";

    if(!OrderSend(request, result))
        Print("OrderSend failed: ", GetLastError());
}

bool IsNewBar()
{
    static datetime lastBar = 0;
    datetime current = iTime(_Symbol, InpTimeframe, 0);
    if(current != lastBar)
    {
        lastBar = current;
        return true;
    }
    return false;
}
'''

_NEWS_FILTER_TEMPLATE = '''\
"""
News Filter Module - Auto-generated by JARVIS AI Trading OS
Generated: {{ timestamp }}
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum, auto
from typing import Optional

logger = logging.getLogger(__name__)


class NewsImpact(Enum):
    LOW = auto()
    MEDIUM = auto()
    HIGH = auto()


@dataclass
class NewsEvent:
    title: str
    currency: str
    impact: NewsImpact
    time: datetime
    actual: Optional[float] = None
    forecast: Optional[float] = None
    previous: Optional[float] = None


@dataclass
class FilterConfig:
    block_high_impact: bool = True
    block_medium_impact: bool = False
    minutes_before: int = 30
    minutes_after: int = 15
    currencies: list[str] = field(default_factory=lambda: ["USD", "EUR", "GBP", "JPY"])


class NewsFilter:
    """Filters trading signals around high-impact news events."""

    def __init__(self, config: Optional[FilterConfig] = None) -> None:
        self.config = config or FilterConfig()
        self._events: list[NewsEvent] = []

    def load_events(self, events: list[NewsEvent]) -> None:
        self._events = sorted(events, key=lambda e: e.time)
        logger.info("Loaded %d news events", len(self._events))

    def is_trading_allowed(self, symbol: str, now: Optional[datetime] = None) -> bool:
        now = now or datetime.utcnow()
        currencies = self._extract_currencies(symbol)
        for event in self._events:
            if event.currency not in currencies:
                continue
            if self.config.block_high_impact and event.impact == NewsImpact.HIGH:
                if self._in_window(now, event.time):
                    logger.info("Trading blocked: %s (%s)", event.title, event.currency)
                    return False
            if self.config.block_medium_impact and event.impact == NewsImpact.MEDIUM:
                if self._in_window(now, event.time):
                    return False
        return True

    def _in_window(self, now: datetime, event_time: datetime) -> bool:
        start = event_time - timedelta(minutes=self.config.minutes_before)
        end = event_time + timedelta(minutes=self.config.minutes_after)
        return start <= now <= end

    @staticmethod
    def _extract_currencies(symbol: str) -> list[str]:
        symbol = symbol.upper().replace("/", "")
        if len(symbol) >= 6:
            return [symbol[:3], symbol[3:6]]
        return [symbol]
'''

_INDICATOR_TEMPLATE = '''\
"""
Custom Indicator: {{ indicator_name }}
Auto-generated by JARVIS AI Trading OS
Generated: {{ timestamp }}
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

import numpy as np
import pandas as pd


@dataclass
class IndicatorConfig:
    period: int = 14
    source: str = "close"
    overbought: float = 70.0
    oversold: float = 30.0


class {{ class_name }}:
    """Custom indicator implementation."""

    def __init__(self, config: Optional[IndicatorConfig] = None) -> None:
        self.config = config or IndicatorConfig()

    def calculate(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()
        src = df[self.config.source]
        df["indicator_value"] = self._compute(src)
        df["indicator_signal"] = np.where(
            df["indicator_value"] > self.config.overbought, -1,
            np.where(df["indicator_value"] < self.config.oversold, 1, 0),
        )
        return df

    def _compute(self, series: pd.Series) -> pd.Series:
        delta = series.diff()
        gain = delta.where(delta > 0, 0.0).rolling(self.config.period).mean()
        loss = (-delta.where(delta < 0, 0.0)).rolling(self.config.period).mean()
        rs = gain / loss.replace(0, np.nan)
        return 100.0 - (100.0 / (1.0 + rs))

    def get_signal(self, df: pd.DataFrame) -> int:
        result = self.calculate(df)
        return int(result["indicator_signal"].iloc[-1])
'''

_WINRATE_OPTIMIZER_TEMPLATE = '''\
"""
Winrate Optimizer - Auto-generated by JARVIS AI Trading OS
Generated: {{ timestamp }}
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


@dataclass
class FilterResult:
    name: str
    original_winrate: float
    filtered_winrate: float
    improvement: float
    trades_removed: int
    trades_remaining: int


class WinrateOptimizer:
    """Analyses past trades and proposes entry filters to improve winrate."""

    def __init__(self, trades: pd.DataFrame) -> None:
        self.trades = trades.copy()

    def analyse(self) -> list[FilterResult]:
        results: list[FilterResult] = []
        original_wr = self._winrate(self.trades)

        filters: list[tuple[str, Any]] = [
            ("spread_filter", self._spread_filter),
            ("session_filter", self._session_filter),
            ("volatility_filter", self._volatility_filter),
            ("trend_filter", self._trend_filter),
        ]

        for name, fn in filters:
            try:
                filtered = fn(self.trades)
                new_wr = self._winrate(filtered)
                results.append(FilterResult(
                    name=name,
                    original_winrate=original_wr,
                    filtered_winrate=new_wr,
                    improvement=new_wr - original_wr,
                    trades_removed=len(self.trades) - len(filtered),
                    trades_remaining=len(filtered),
                ))
            except Exception:
                logger.exception("Filter %s failed", name)

        return sorted(results, key=lambda r: r.improvement, reverse=True)

    @staticmethod
    def _winrate(df: pd.DataFrame) -> float:
        if df.empty:
            return 0.0
        return float((df["pnl"] > 0).mean() * 100)

    @staticmethod
    def _spread_filter(df: pd.DataFrame) -> pd.DataFrame:
        if "spread" in df.columns:
            median = df["spread"].median()
            return df[df["spread"] <= median * 1.5]
        return df

    @staticmethod
    def _session_filter(df: pd.DataFrame) -> pd.DataFrame:
        if "hour" in df.columns:
            return df[df["hour"].between(8, 17)]
        return df

    @staticmethod
    def _volatility_filter(df: pd.DataFrame) -> pd.DataFrame:
        if "atr" in df.columns:
            q25, q75 = df["atr"].quantile(0.25), df["atr"].quantile(0.75)
            return df[df["atr"].between(q25, q75)]
        return df

    @staticmethod
    def _trend_filter(df: pd.DataFrame) -> pd.DataFrame:
        if "adx" in df.columns:
            return df[df["adx"] > 20]
        return df
'''

_TELEGRAM_SIGNAL_BOT_TEMPLATE = '''\
"""
Telegram Signal Bot - Auto-generated by JARVIS AI Trading OS
Generated: {{ timestamp }}
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field
from typing import Any, Optional

logger = logging.getLogger(__name__)


@dataclass
class SignalMessage:
    symbol: str
    direction: str
    entry: float
    stop_loss: float
    take_profit: float
    confidence: float = 0.0
    timeframe: str = "H1"

    def format(self) -> str:
        arrow = "\\u2B06" if self.direction.upper() == "BUY" else "\\u2B07"
        return (
            f"{arrow} *{self.direction.upper()} {self.symbol}*\\n"
            f"Entry: `{self.entry:.5f}`\\n"
            f"SL: `{self.stop_loss:.5f}`\\n"
            f"TP: `{self.take_profit:.5f}`\\n"
            f"Timeframe: {self.timeframe}\\n"
            f"Confidence: {self.confidence:.0%}"
        )


@dataclass
class BotConfig:
    token: str = ""
    chat_ids: list[str] = field(default_factory=list)
    parse_mode: str = "Markdown"


class TelegramSignalBot:
    """Sends trading signals to Telegram channels/groups."""

    def __init__(self, config: Optional[BotConfig] = None) -> None:
        self.config = config or BotConfig()
        self._session: Any = None

    async def send_signal(self, signal: SignalMessage) -> bool:
        text = signal.format()
        success = True
        for chat_id in self.config.chat_ids:
            try:
                await self._send_message(chat_id, text)
            except Exception:
                logger.exception("Failed to send signal to %s", chat_id)
                success = False
        return success

    async def send_text(self, text: str) -> None:
        for chat_id in self.config.chat_ids:
            await self._send_message(chat_id, text)

    async def _send_message(self, chat_id: str, text: str) -> None:
        import aiohttp
        url = f"https://api.telegram.org/bot{self.config.token}/sendMessage"
        payload = {"chat_id": chat_id, "text": text, "parse_mode": self.config.parse_mode}
        async with aiohttp.ClientSession() as session:
            async with session.post(url, json=payload) as resp:
                if resp.status != 200:
                    body = await resp.text()
                    logger.error("Telegram API error %d: %s", resp.status, body)
                    raise RuntimeError(f"Telegram API error {resp.status}")
'''

_TRAILING_STOP_TEMPLATE = '''\
"""
Trailing Stop Module - Auto-generated by JARVIS AI Trading OS
Generated: {{ timestamp }}
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from enum import Enum, auto
from typing import Optional

logger = logging.getLogger(__name__)


class TrailingMethod(Enum):
    FIXED_PIPS = auto()
    ATR_BASED = auto()
    PERCENTAGE = auto()
    CHANDELIER = auto()


@dataclass
class TrailingConfig:
    method: TrailingMethod = TrailingMethod.ATR_BASED
    distance_pips: float = 20.0
    atr_multiplier: float = 2.0
    percentage: float = 1.0
    activation_pips: float = 10.0
    step_pips: float = 5.0


class TrailingStop:
    """Manages trailing stop-loss for open positions."""

    def __init__(self, config: Optional[TrailingConfig] = None) -> None:
        self.config = config or TrailingConfig()
        self._highest_price: dict[str, float] = {}
        self._lowest_price: dict[str, float] = {}

    def update(
        self,
        ticket: str,
        direction: str,
        current_price: float,
        current_sl: float,
        atr: float = 0.0,
        pip_value: float = 0.0001,
    ) -> Optional[float]:
        if direction.upper() == "BUY":
            return self._trail_buy(ticket, current_price, current_sl, atr, pip_value)
        return self._trail_sell(ticket, current_price, current_sl, atr, pip_value)

    def _trail_buy(
        self, ticket: str, price: float, sl: float, atr: float, pip: float
    ) -> Optional[float]:
        self._highest_price[ticket] = max(self._highest_price.get(ticket, price), price)
        highest = self._highest_price[ticket]
        distance = self._get_distance(atr, pip)

        new_sl = highest - distance
        if new_sl > sl:
            logger.info("Trailing BUY %s: SL %.5f -> %.5f", ticket, sl, new_sl)
            return round(new_sl, 5)
        return None

    def _trail_sell(
        self, ticket: str, price: float, sl: float, atr: float, pip: float
    ) -> Optional[float]:
        self._lowest_price[ticket] = min(self._lowest_price.get(ticket, price), price)
        lowest = self._lowest_price[ticket]
        distance = self._get_distance(atr, pip)

        new_sl = lowest + distance
        if new_sl < sl:
            logger.info("Trailing SELL %s: SL %.5f -> %.5f", ticket, sl, new_sl)
            return round(new_sl, 5)
        return None

    def _get_distance(self, atr: float, pip: float) -> float:
        if self.config.method == TrailingMethod.ATR_BASED and atr > 0:
            return atr * self.config.atr_multiplier
        if self.config.method == TrailingMethod.PERCENTAGE:
            return self.config.percentage / 100.0
        return self.config.distance_pips * pip

    def reset(self, ticket: str) -> None:
        self._highest_price.pop(ticket, None)
        self._lowest_price.pop(ticket, None)
'''

_DRAWDOWN_OPTIMIZER_TEMPLATE = '''\
"""
Drawdown Optimizer - Auto-generated by JARVIS AI Trading OS
Generated: {{ timestamp }}
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Optional

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


@dataclass
class DrawdownMetrics:
    max_drawdown_pct: float
    max_drawdown_abs: float
    avg_drawdown_pct: float
    max_drawdown_duration_bars: int
    recovery_factor: float
    calmar_ratio: float


class DrawdownOptimizer:
    """Analyses and optimizes strategy drawdown characteristics."""

    def __init__(self, equity_curve: pd.Series) -> None:
        self.equity = equity_curve.copy()

    def analyse(self) -> DrawdownMetrics:
        peak = self.equity.cummax()
        dd = (self.equity - peak) / peak
        abs_dd = self.equity - peak
        max_dd_pct = float(dd.min())
        max_dd_abs = float(abs_dd.min())
        avg_dd_pct = float(dd[dd < 0].mean()) if (dd < 0).any() else 0.0

        in_dd = dd < 0
        groups = (~in_dd).cumsum()
        dd_durations = in_dd.groupby(groups).sum()
        max_duration = int(dd_durations.max()) if not dd_durations.empty else 0

        total_return = (self.equity.iloc[-1] / self.equity.iloc[0]) - 1 if self.equity.iloc[0] != 0 else 0.0
        recovery_factor = abs(total_return / max_dd_pct) if max_dd_pct != 0 else 0.0
        calmar = abs(total_return / max_dd_pct) if max_dd_pct != 0 else 0.0

        return DrawdownMetrics(
            max_drawdown_pct=round(max_dd_pct * 100, 2),
            max_drawdown_abs=round(max_dd_abs, 2),
            avg_drawdown_pct=round(avg_dd_pct * 100, 2),
            max_drawdown_duration_bars=max_duration,
            recovery_factor=round(recovery_factor, 2),
            calmar_ratio=round(calmar, 2),
        )

    def suggest_improvements(self) -> list[str]:
        metrics = self.analyse()
        suggestions: list[str] = []
        if metrics.max_drawdown_pct < -10:
            suggestions.append("Consider reducing position size to limit drawdown")
        if metrics.max_drawdown_duration_bars > 100:
            suggestions.append("Add time-based exit to limit drawdown duration")
        if metrics.recovery_factor < 2:
            suggestions.append("Improve reward-to-risk ratio for faster recovery")
        if not suggestions:
            suggestions.append("Drawdown profile is within acceptable limits")
        return suggestions
'''

_OPTIMIZER_CONFIG_TEMPLATE = '''\
"""
Strategy Optimizer Configuration - Auto-generated by JARVIS AI Trading OS
Generated: {{ timestamp }}
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class OptimizationRange:
    name: str
    min_value: float
    max_value: float
    step: float


@dataclass
class OptimizerConfig:
    strategy_name: str = "trend_following"
    symbol: str = "EURUSD"
    timeframe: str = "H1"
    start_date: str = "2024-01-01"
    end_date: str = "2025-01-01"
    n_trials: int = 200
    n_splits: int = 5
    out_of_sample_pct: float = 0.3
    objective: str = "sharpe_ratio"
    parameters: list[OptimizationRange] = field(default_factory=lambda: [
        OptimizationRange("sl_pips", 10.0, 50.0, 5.0),
        OptimizationRange("tp_pips", 15.0, 100.0, 5.0),
        OptimizationRange("fast_period", 5.0, 30.0, 1.0),
        OptimizationRange("slow_period", 20.0, 100.0, 5.0),
        OptimizationRange("atr_multiplier", 1.0, 4.0, 0.5),
    ])
'''


class CodeGenerator:
    """Generates Python and MQL5 files from templates."""

    def __init__(self, output_root: str | Path = "generated") -> None:
        self.output_root = Path(output_root)

    def _save(self, relative_path: str, content: str, language: str, description: str) -> GeneratedFile:
        full_path = self.output_root / relative_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding="utf-8")
        logger.info("Generated %s -> %s", description, full_path)
        return GeneratedFile(
            path=str(full_path),
            language=language,
            description=description,
            content=content,
        )

    def _ctx(self, **extra: Any) -> dict[str, Any]:
        base: dict[str, Any] = {"timestamp": datetime.utcnow().isoformat(timespec="seconds")}
        base.update(extra)
        return base

    def generate_bot(
        self,
        asset: str = "EURUSD",
        strategy: str = "trend_following",
        timeframe: str = "H1",
        sl_pips: float = 20.0,
        tp_pips: float = 40.0,
        fast_period: int = 12,
        slow_period: int = 26,
    ) -> list[GeneratedFile]:
        class_name = "".join(w.capitalize() for w in strategy.split("_")) + "Strategy"
        strategy_display = strategy.replace("_", " ").title()
        tf_mql = timeframe.upper().replace("M", "M").replace("H", "H")

        ctx = self._ctx(
            asset=asset,
            strategy_display=strategy_display,
            timeframe=timeframe,
            timeframe_mql=tf_mql,
            class_name=class_name,
            sl_pips=sl_pips,
            tp_pips=tp_pips,
            fast_period=fast_period,
            slow_period=slow_period,
        )

        files: list[GeneratedFile] = []
        safe_strategy = strategy.lower().replace(" ", "_")
        safe_asset = asset.upper()

        py_content = _render(_PYTHON_STRATEGY_TEMPLATE, ctx)
        files.append(self._save(
            f"strategies/{safe_asset}_{safe_strategy}.py",
            py_content,
            "python",
            f"Python strategy: {strategy_display} for {asset}",
        ))

        ea_name = f"{safe_asset}_{safe_strategy}_EA"
        ctx["ea_name"] = ea_name
        mql_content = _render(_MQL5_EA_TEMPLATE, ctx)
        files.append(self._save(
            f"mql5/{ea_name}.mq5",
            mql_content,
            "mql5",
            f"MQL5 Expert Advisor: {ea_name}",
        ))

        return files

    def generate_optimizer_config(self) -> list[GeneratedFile]:
        ctx = self._ctx()
        content = _render(_OPTIMIZER_CONFIG_TEMPLATE, ctx)
        return [self._save("config/optimizer_config.py", content, "python", "Optimizer configuration")]

    def generate_news_filter(self) -> list[GeneratedFile]:
        ctx = self._ctx()
        content = _render(_NEWS_FILTER_TEMPLATE, ctx)
        return [self._save("modules/news_filter.py", content, "python", "News filter module")]

    def generate_indicator(self, name: str = "custom_indicator") -> list[GeneratedFile]:
        class_name = "".join(w.capitalize() for w in name.split("_")) + "Indicator"
        ctx = self._ctx(indicator_name=name, class_name=class_name)
        content = _render(_INDICATOR_TEMPLATE, ctx)
        return [self._save(f"indicators/{name}.py", content, "python", f"Indicator: {name}")]

    def generate_winrate_optimizer(self) -> list[GeneratedFile]:
        ctx = self._ctx()
        content = _render(_WINRATE_OPTIMIZER_TEMPLATE, ctx)
        return [self._save("optimization/winrate_optimizer.py", content, "python", "Winrate optimizer")]

    def generate_telegram_signal_bot(self) -> list[GeneratedFile]:
        ctx = self._ctx()
        content = _render(_TELEGRAM_SIGNAL_BOT_TEMPLATE, ctx)
        return [self._save("bots/telegram_signal_bot.py", content, "python", "Telegram signal bot")]

    def generate_trailing_stop_module(self) -> list[GeneratedFile]:
        ctx = self._ctx()
        content = _render(_TRAILING_STOP_TEMPLATE, ctx)
        return [self._save("modules/trailing_stop.py", content, "python", "Trailing stop module")]

    def generate_drawdown_optimizer(self) -> list[GeneratedFile]:
        ctx = self._ctx()
        content = _render(_DRAWDOWN_OPTIMIZER_TEMPLATE, ctx)
        return [self._save("optimization/drawdown_optimizer.py", content, "python", "Drawdown optimizer")]
